; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2025-12-24 at 10:09:25
; total layer number: 1
; filament_density: 1.31
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 664
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAABt0lEQVR4Ae2YzUoCURzF//StUaZmmn
; 1oCi2iwE2LNiG4SEJiCBKCAqlNHxvBVSC5iApa5KpFKx+hR/ARegQfwUcwTiAMotOMM6cZ5f7gIKh3
; ODP3njtnRkShUCgU48KE37cko8pyUaunP987+BypE5ndWMskXqotmO9qvVr5xvfidQK5w7LeuF5b9e
; c2fvfkbMBUvHLXHGReL/xvKhxKildYONgvmTHeOxsYJ26zUjpvWDWvF8a7sqT6BXVYIeDzmV1N/otg
; 4ajmhPF+ARcmuOq4Wk6bhxKvj+25VDIrLIy2R7uKXJw1hAUCFru9+mIYT328dahr37edzmJtMszjXk
; Ddfbo9hqFgPlcTFsyg4rgzq1FeH2IGNXxaqAsLKz3GqpAh6vY4TI8xq9j9dVOY2O0xRqIWNSd7TL+g
; Uqsyo8d0FTrJ84KqeswA0XsMK6j0HsMMKu4Zk4HFpDDBNsYoYtQe0wtmIV6+aTphnN5jBoEcoFnamQ
; 2MF7dBt998emhZMY6TxjjxCpiNyGWxYcY8vcfYwb+3oxktKU+8cPqL6Wgk0/us61pQ7RDSjn8DTn3g
; UCgUCoXCAj9yOADnQ5y8kAAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 3368
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAJpUlEQVR4Ae3c/2pW9x0H8NPSakys1c
; SfsTHGTJGZYgQ3mH/YwIRNmGixrN1GaZD+oRlMIYJlKLEUu+nY3Bgd7C8vwUvIJXgJXoKX8MyvEBfU
; avx+n/N5zjnP6wXvS3hOznnn+/5WFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAdNyO3/xqZcuR2YUKoKk2T+2f/+jm8qPZ//6jN3P/zpMPf3n62ruj
; W7ZXAE2SHk7pQfViJpeXVt+bGD9YAQxaeoPae+XSw1c9rNay9rZVAQxK6qnSw+h1D6v1SQ82n4hAuJ
; 2/vXB/ow+q9Zn+/ubjsfm5CxVA3VKxnh46OQ+r9Z+I6YHnbQuozY8V67lJhXx6AFYA/ZLehNLDpZ8P
; K4U80Hcf/OJni3U8qBx/APpq9+LvHkQ8rNa/bSnkgbfSj2K9JAp5YEPSDnBQD6r1SRMfhTzwSut3gE
; 2JPSLwkn4fV+h3FPLAhnaATXrbSv+xrIDhkz4B32YH2JSk/1z6RIQhkrsDbEpS1+b4A3RcE4v13Cjk
; ocOaXqznRiEPHdKmYr30basC2iv1PG168PTjbcsnIrRQ9A6wSW9bCnloiUHvAJsSe0RouKbsAJsSe0
; RooC4dV+h3HH+ABunqcYV+x/EHGKD0xjCsxXpu7BFhABTrZbFHhCBt3wE2JfaIUCPFev+jkIcaKNbr
; jUIe+mAYdoBNiT0iFNhyZHahjRfstT32iPCWFOuDjT0ibIDjCs2KPSL8CMV6M2OPCOukv+CpN2nTj3
; jYopCHp9JMpE0/3GGP4w8MLTvAdkYhz1BRrHcjCnk6zwV73YpCnk6yA+xu7BHpFMcVhiMKeVrNDnD4
; 4oJAWskOcLjjgkBaww5QUlwQSKMp1uXFKORpJMW6vC6pkHf8gYGzA5SNxh6RgbIDlJy4IJBwdoCSm+
; m7K71Nk3sXKqibHaCUZPdXX6y+t2O7Lov62QFKbg7+/bveB6d+fr+CujmuICXZf+Pqk/d371qooG6O
; K0huDv1wrzdx8dxqBXVL/8VRrEtupr79prd5Znqxgrop1qUku/7wmWKdGHaAkptUrG89eWKlgrop1q
; Ukk8t/VKwTQ7EuuUlvVR+e+eRBBXVzwZ6U5KNb13veqgjhgj3JTTqukIr1d8dGD1ZQN8W65CZ9Ao4d
; n3PjAvVzXEFKsufrLx85rkAIO0DJTXqr2nb6lB0g9UvFuuMKkhs7QMK4YE9yk4r1nZ9/agdIDDtAyc
; 2BOzd7I4dnFyuom2JdSmIHSBjHFSQ3LtgjjB2glMQOkDB2gJKb9FY1fv6sYp362QFKSewACWMHKLmx
; AySUYl1y44I9wjiuICXZd/WyYp0YinXJjQv2CJOK9cnlpdU2/UCkOVGsE8YOUHJjB0goO0DJzfTdld
; 7osaMu2KN+inUpye6vvrADJIYL9iQ3doCEsQOUkrhgjzCOK0huUrE+cfGcYp36peMKinXJzdS33/Q2
; z0wvVlA3xbqUxA6QMHaAkhs7QMIo1qUkLtgjjGJdcmMHSBgX7ElJ7AAJMzY/d8EFe5KTtR2gYp0Qji
; tIbuwACeO4gpTEDpAwdoCSm1Ssbzt9yg6Q+jmuICWxAySMC/YkN3aAhLEDlJLYARJGsS4lSTtAxToh
; 7AAlNy7YI4xiXUpiB0gYO0DJTXqrGj9/VrFO/ewApSR2gITZcmR2wQ5QcpKOK7hgjzCKdclN+gQcOz
; 5nB0j9HFeQkuxduvTYcQVCKNYlNy7YI0wq1ieXl1bb9AOR5kSxThg7QMnN2gV7FUSwA5TcpAv2Rg7P
; LlZQN8W6lMQFe4RxwZ7kxg6QMHaAUhIX7BHGcQXJTSrW7QAJYQcoJXHBHmHsAKUkdoCEsQOU3KRife
; vJEysV1E2xLiVxwR5hFOuSGztAwtgBSknsAAljByi5WdsBKtYJYQcouUk7wNFjR12wR/3sAKUkdoCE
; sQOU3NgBEsZxBSmJHSBhHFeQ3KRifeLiOTtA6peOKyjWJTd2gIRRrEtJ0g5QsU4IO0DJjR0gYRTrUh
; I7QMIo1iU3doCEccGelMQOkDAu2JPcpOMKLtgjjGJdcpM+AceOz9kBUj/HFaQke77+8pHjCoRQrEtu
; 0lvVttOn7ACpXyrWHVeQ3NgBEsYFe5KbtQv2KohgByi5OXDnZm/k8OxiBXVTrEtJXLBHGBfsSW5csE
; cYO0ApiR0gYRxXkNzM/OsvvfHzZxXr1M8OUEqSLtjzVkUIO0ApiR0gYewAJTcu2COM4wpSkn1XLyvW
; iaFYl9y4YI8wqVifXF5abdMPRJoTF+wRxg5QcrO2A1SsE8IOUHIzfXelN3rsqAv2qJ9iXUpiB0iYkd
; mZhUP/+VurfiDSjNgBMhDbz3xyf+af37fqxyKDjQv2GKj39+yan7p1/Ym3LXldUrE+cfGcHSDNMH7u
; 1w8O/fuvrfoRSUzSDnDzzPRiBU0y8pOZC1O3b9gMyvPYAdJo702Mz+/6/WcPfSIOd+wAaZVUyB+8d7
; tVPzLpT1ywRyulQn7/jT899rY1HLEDpBMU8t2PHSCd8qyQv3VdId+x2AHSWamQf/a25ROxE7EDZCiM
; nfj42oHv/uxtq8WxA2SopLetyWtXFPItSyrWt50+ZQfIcLJHbE/sAKH6/x6xTT/eYYodILzgnU2btj
; v+0LzYAcJr2CM2J2kHqFiHN7BHHGxcsAcZnu0Rn/542vRjb3vsAKGAPWJM0h+G8fNnFevQDwr5+mIH
; CDVQyPc36biCC/agRqmQ3/n5pwr5wqRPwLHjc3aAEGHryXl7xMzsu3r5ieMKECwV8k//q6WQ32BcsA
; cNkAp5e8TXR7EODbJ5av+CPeLLWbtgrwKa5fkFgY4/PEu6YG/k8OxiBTSXCwJdsAetkt629i5dejRs
; hbwdILTYMF0Q6II96IC1CwK7+rblgj3ooC4W8i7Ygw7r0h7RDhCGQNsvCEzF+taTJ1YqYHikQr5txx
; 9csAdDrC0XBNoBAs81uZC3AwRe0rQ94toOULEOvNLzPeKAPxHTDnD02FEX7AFvNsg9oh0g8NbS29bk
; tSthhbwdIFAsYo9oBwj0TV17RDtAoBbvbNq0vZ/HH+wAgdr1Y4+YdoCKdSBE7h7RDhAYmFTIH7x3e0
; MPKztAYODetEdMb1U7zp55WAE0xasKeTtAoLGeFfLp+MMP91ywBzRfKuRHP/6pHSAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ33PxMQyFgQPWijAA
; AAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.48mm
; top infill extrusion width = 0.38mm
; first layer extrusion width = 0.48mm

; EXECUTABLE_BLOCK_START
M73 P0 R2
;TYPE:Custom
M115 U3.2.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M204 S10000 T1500 ; MK2 firmware only supports the old M204 format
M104 S230 ; set extruder temp
M140 S55 ; set bed temp
M190 S55 ; wait for bed temp
M109 S230 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Z0.2 F720
G1 Y-2 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
M73 P2 R2
G92 E0
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
SET_PRESSURE_ADVANCE ADVANCE=0.0775; Override pressure advance value
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2

G1 E-.4 F2100
M73 P4 R2
;AFTER_LAYER_CHANGE
;0.2
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=800 ACCEL_TO_DECEL=400
; printing object Cube id:106035774743264 copy 0
G1 Z.6 F10800
G1 X169.301 Y119.301
G1 Z.6
G1 Z.2
G1 E.4 F2100
;TYPE:Inner wall
;WIDTH:0.479999
G1 F1200
M73 P5 R2
G1 X80.699 Y119.301 E3.15572
G1 X80.699 Y90.699 E1.01873
M73 P8 R2
G1 X169.301 Y90.699 E3.15572
M73 P9 R2
G1 X169.301 Y119.261 E1.01731
M73 P12 R2
G1 X169.76 Y119.76 F10800
M73 P13 R2
;TYPE:Outer wall
G1 F1200
G1 X80.24 Y119.76 E3.18838
G1 X80.24 Y90.24 E1.0514
M73 P16 R2
G1 X169.76 Y90.24 E3.18838
M73 P17 R2
G1 X169.76 Y119.72 E1.04997
M73 P20 R1
G1 E-.28 F2100
M73 P21 R1
;WIPE_START
G1 F1200
G1 X168.76 Y119.72 E-.12
;WIPE_END
G1 Z.6 F10800
G1 X169.17 Y91.718 Z.6
G1 Z.2
G1 E.4 F2100
;TYPE:Bottom surface
;WIDTH:0.482111
G1 F3600
G1 X168.479 Y91.026 E.03499
G1 X167.858 Y91.026 E.02223
G1 X168.974 Y92.142 E.05647
G1 X168.974 Y92.763 E.02223
G1 X167.237 Y91.026 E.08791
G1 X166.616 Y91.026 E.02223
G1 X168.974 Y93.384 E.11934
G1 X168.974 Y94.005 E.02223
G1 X165.995 Y91.026 E.15078
G1 X165.373 Y91.026 E.02223
M73 P22 R1
G1 X168.974 Y94.627 E.18222
G1 X168.974 Y95.248 E.02223
G1 X164.752 Y91.026 E.21365
G1 X164.131 Y91.026 E.02223
G1 X168.974 Y95.869 E.24509
G1 X168.974 Y96.49 E.02223
G1 X163.51 Y91.026 E.27652
G1 X162.889 Y91.026 E.02223
G1 X168.974 Y97.111 E.30796
G1 X168.974 Y97.732 E.02223
G1 X162.268 Y91.026 E.3394
G1 X161.647 Y91.026 E.02223
G1 X168.974 Y98.353 E.37083
G1 X168.974 Y98.974 E.02223
M73 P23 R1
G1 X161.026 Y91.026 E.40227
G1 X160.405 Y91.026 E.02223
G1 X168.974 Y99.595 E.4337
G1 X168.974 Y100.217 E.02223
G1 X159.783 Y91.026 E.46514
G1 X159.162 Y91.026 E.02223
G1 X168.974 Y100.838 E.49658
G1 X168.974 Y101.459 E.02223
G1 X158.541 Y91.026 E.52801
G1 X157.92 Y91.026 E.02223
M73 P24 R1
G1 X168.974 Y102.08 E.55945
G1 X168.974 Y102.701 E.02223
G1 X157.299 Y91.026 E.59088
G1 X156.678 Y91.026 E.02223
G1 X168.974 Y103.322 E.62232
G1 X168.974 Y103.943 E.02223
G1 X156.057 Y91.026 E.65376
G1 X155.436 Y91.026 E.02223
M73 P25 R1
G1 X168.974 Y104.564 E.68519
G1 X168.974 Y105.185 E.02223
G1 X154.815 Y91.026 E.71663
G1 X154.193 Y91.026 E.02223
G1 X168.974 Y105.807 E.74806
G1 X168.974 Y106.428 E.02223
G1 X153.572 Y91.026 E.7795
G1 X152.951 Y91.026 E.02223
M73 P26 R1
G1 X168.974 Y107.049 E.81094
G1 X168.974 Y107.67 E.02223
G1 X152.33 Y91.026 E.84237
G1 X151.709 Y91.026 E.02223
G1 X168.974 Y108.291 E.87381
G1 X168.974 Y108.912 E.02223
M73 P27 R1
G1 X151.088 Y91.026 E.90524
G1 X150.467 Y91.026 E.02223
G1 X168.974 Y109.533 E.93668
G1 X168.974 Y110.154 E.02223
G1 X149.846 Y91.026 E.96812
G1 X149.225 Y91.026 E.02223
M73 P28 R1
G1 X168.974 Y110.775 E.99955
G1 X168.974 Y111.397 E.02223
G1 X148.603 Y91.026 E1.03099
G1 X147.982 Y91.026 E.02223
G1 X168.974 Y112.018 E1.06242
M73 P29 R1
G1 X168.974 Y112.639 E.02223
G1 X147.361 Y91.026 E1.09386
G1 X146.74 Y91.026 E.02223
G1 X168.974 Y113.26 E1.1253
G1 X168.974 Y113.881 E.02223
M73 P30 R1
G1 X146.119 Y91.026 E1.15673
G1 X145.498 Y91.026 E.02223
G1 X168.974 Y114.502 E1.18817
G1 X168.974 Y115.123 E.02223
M73 P31 R1
G1 X144.877 Y91.026 E1.2196
G1 X144.256 Y91.026 E.02223
G1 X168.974 Y115.744 E1.25104
G1 X168.974 Y116.365 E.02223
G1 X143.635 Y91.026 E1.28248
G1 X143.013 Y91.026 E.02223
M73 P32 R1
G1 X168.974 Y116.987 E1.31391
G1 X168.974 Y117.608 E.02223
G1 X142.392 Y91.026 E1.34535
G1 X141.771 Y91.026 E.02223
M73 P33 R1
G1 X168.974 Y118.229 E1.37678
G1 X168.974 Y118.85 E.02223
G1 X141.15 Y91.026 E1.40822
G1 X140.529 Y91.026 E.02223
M73 P34 R1
G1 X168.476 Y118.974 E1.41449
G1 X167.855 Y118.974 E.02223
G1 X139.908 Y91.026 E1.41449
G1 X139.287 Y91.026 E.02223
M73 P35 R1
G1 X167.234 Y118.974 E1.41449
G1 X166.613 Y118.974 E.02223
G1 X138.666 Y91.026 E1.41449
G1 X138.045 Y91.026 E.02223
M73 P36 R1
G1 X165.992 Y118.974 E1.41449
G1 X165.371 Y118.974 E.02223
G1 X137.424 Y91.026 E1.41449
G1 X136.802 Y91.026 E.02223
M73 P37 R1
G1 X164.75 Y118.974 E1.41449
G1 X164.129 Y118.974 E.02223
G1 X136.181 Y91.026 E1.41449
G1 X135.56 Y91.026 E.02223
M73 P38 R1
G1 X163.507 Y118.974 E1.41449
G1 X162.886 Y118.974 E.02223
G1 X134.939 Y91.026 E1.41449
G1 X134.318 Y91.026 E.02223
M73 P39 R1
G1 X162.265 Y118.974 E1.41449
G1 X161.644 Y118.974 E.02223
G1 X133.697 Y91.026 E1.41449
G1 X133.076 Y91.026 E.02223
M73 P40 R1
G1 X161.023 Y118.974 E1.41449
G1 X160.402 Y118.974 E.02223
G1 X132.455 Y91.026 E1.41449
G1 X131.834 Y91.026 E.02223
M73 P41 R1
G1 X159.781 Y118.974 E1.41449
G1 X159.16 Y118.974 E.02223
G1 X131.212 Y91.026 E1.41449
G1 X130.591 Y91.026 E.02223
M73 P42 R1
G1 X158.539 Y118.974 E1.41449
G1 X157.917 Y118.974 E.02223
G1 X129.97 Y91.026 E1.41449
M73 P43 R1
G1 X129.349 Y91.026 E.02223
G1 X157.296 Y118.974 E1.41449
G1 X156.675 Y118.974 E.02223
M73 P44 R1
G1 X128.728 Y91.026 E1.41449
G1 X128.107 Y91.026 E.02223
G1 X156.054 Y118.974 E1.41449
G1 X155.433 Y118.974 E.02223
M73 P45 R1
G1 X127.486 Y91.026 E1.41449
G1 X126.865 Y91.026 E.02223
G1 X154.812 Y118.974 E1.41449
G1 X154.191 Y118.974 E.02223
M73 P46 R1
G1 X126.244 Y91.026 E1.41449
G1 X125.622 Y91.026 E.02223
G1 X153.57 Y118.974 E1.41449
G1 X152.949 Y118.974 E.02223
M73 P47 R1
G1 X125.001 Y91.026 E1.41449
G1 X124.38 Y91.026 E.02223
G1 X152.328 Y118.974 E1.41449
G1 X151.706 Y118.974 E.02223
M73 P48 R1
G1 X123.759 Y91.026 E1.41449
G1 X123.138 Y91.026 E.02223
G1 X151.085 Y118.974 E1.41449
G1 X150.464 Y118.974 E.02223
M73 P49 R1
G1 X122.517 Y91.026 E1.41449
G1 X121.896 Y91.026 E.02223
G1 X149.843 Y118.974 E1.41449
G1 X149.222 Y118.974 E.02223
M73 P50 R1
G1 X121.275 Y91.026 E1.41449
G1 X120.654 Y91.026 E.02223
G1 X148.601 Y118.974 E1.41449
G1 X147.98 Y118.974 E.02223
M73 P51 R1
G1 X120.032 Y91.026 E1.41449
G1 X119.411 Y91.026 E.02223
G1 X147.359 Y118.974 E1.41449
G1 X146.738 Y118.974 E.02223
M73 P52 R1
G1 X118.79 Y91.026 E1.41449
G1 X118.169 Y91.026 E.02223
G1 X146.116 Y118.974 E1.41449
G1 X145.495 Y118.974 E.02223
M73 P53 R1
G1 X117.548 Y91.026 E1.41449
G1 X116.927 Y91.026 E.02223
G1 X144.874 Y118.974 E1.41449
G1 X144.253 Y118.974 E.02223
M73 P54 R1
G1 X116.306 Y91.026 E1.41449
G1 X115.685 Y91.026 E.02223
G1 X143.632 Y118.974 E1.41449
G1 X143.011 Y118.974 E.02223
M73 P55 R1
G1 X115.064 Y91.026 E1.41449
G1 X114.442 Y91.026 E.02223
G1 X142.39 Y118.974 E1.41449
G1 X141.769 Y118.974 E.02223
M73 P56 R1
G1 X113.821 Y91.026 E1.41449
G1 X113.2 Y91.026 E.02223
G1 X141.148 Y118.974 E1.41449
G1 X140.526 Y118.974 E.02223
M73 P57 R1
G1 X112.579 Y91.026 E1.41449
G1 X111.958 Y91.026 E.02223
G1 X139.905 Y118.974 E1.41449
G1 X139.284 Y118.974 E.02223
M73 P58 R1
G1 X111.337 Y91.026 E1.41449
G1 X110.716 Y91.026 E.02223
G1 X138.663 Y118.974 E1.41449
G1 X138.042 Y118.974 E.02223
M73 P59 R1
G1 X110.095 Y91.026 E1.41449
G1 X109.474 Y91.026 E.02223
M73 P59 R0
G1 X137.421 Y118.974 E1.41449
G1 X136.8 Y118.974 E.02223
M73 P60 R0
G1 X108.852 Y91.026 E1.41449
G1 X108.231 Y91.026 E.02223
G1 X136.179 Y118.974 E1.41449
G1 X135.558 Y118.974 E.02223
M73 P61 R0
G1 X107.61 Y91.026 E1.41449
G1 X106.989 Y91.026 E.02223
G1 X134.936 Y118.974 E1.41449
G1 X134.315 Y118.974 E.02223
M73 P62 R0
G1 X106.368 Y91.026 E1.41449
G1 X105.747 Y91.026 E.02223
G1 X133.694 Y118.974 E1.41449
G1 X133.073 Y118.974 E.02223
M73 P63 R0
G1 X105.126 Y91.026 E1.41449
G1 X104.505 Y91.026 E.02223
G1 X132.452 Y118.974 E1.41449
G1 X131.831 Y118.974 E.02223
M73 P64 R0
G1 X103.884 Y91.026 E1.41449
G1 X103.262 Y91.026 E.02223
G1 X131.21 Y118.974 E1.41449
G1 X130.589 Y118.974 E.02223
M73 P65 R0
G1 X102.641 Y91.026 E1.41449
G1 X102.02 Y91.026 E.02223
G1 X129.968 Y118.974 E1.41449
G1 X129.346 Y118.974 E.02223
M73 P66 R0
G1 X101.399 Y91.026 E1.41449
G1 X100.778 Y91.026 E.02223
G1 X128.725 Y118.974 E1.41449
G1 X128.104 Y118.974 E.02223
M73 P67 R0
G1 X100.157 Y91.026 E1.41449
G1 X99.536 Y91.026 E.02223
G1 X127.483 Y118.974 E1.41449
G1 X126.862 Y118.974 E.02223
M73 P68 R0
G1 X98.915 Y91.026 E1.41449
G1 X98.294 Y91.026 E.02223
G1 X126.241 Y118.974 E1.41449
G1 X125.62 Y118.974 E.02223
M73 P69 R0
G1 X97.672 Y91.026 E1.41449
G1 X97.051 Y91.026 E.02223
G1 X124.999 Y118.974 E1.41449
G1 X124.378 Y118.974 E.02223
M73 P70 R0
G1 X96.43 Y91.026 E1.41449
G1 X95.809 Y91.026 E.02223
G1 X123.756 Y118.974 E1.41449
G1 X123.135 Y118.974 E.02223
M73 P71 R0
G1 X95.188 Y91.026 E1.41449
G1 X94.567 Y91.026 E.02223
G1 X122.514 Y118.974 E1.41449
G1 X121.893 Y118.974 E.02223
M73 P72 R0
G1 X93.946 Y91.026 E1.41449
G1 X93.325 Y91.026 E.02223
G1 X121.272 Y118.974 E1.41449
G1 X120.651 Y118.974 E.02223
M73 P73 R0
G1 X92.704 Y91.026 E1.41449
G1 X92.082 Y91.026 E.02223
G1 X120.03 Y118.974 E1.41449
G1 X119.409 Y118.974 E.02223
M73 P74 R0
G1 X91.461 Y91.026 E1.41449
G1 X90.84 Y91.026 E.02223
G1 X118.788 Y118.974 E1.41449
G1 X118.166 Y118.974 E.02223
M73 P75 R0
G1 X90.219 Y91.026 E1.41449
G1 X89.598 Y91.026 E.02223
G1 X117.545 Y118.974 E1.41449
G1 X116.924 Y118.974 E.02223
M73 P76 R0
G1 X88.977 Y91.026 E1.41449
G1 X88.356 Y91.026 E.02223
G1 X116.303 Y118.974 E1.41449
G1 X115.682 Y118.974 E.02223
M73 P77 R0
G1 X87.735 Y91.026 E1.41449
G1 X87.114 Y91.026 E.02223
G1 X115.061 Y118.974 E1.41449
G1 X114.44 Y118.974 E.02223
M73 P78 R0
G1 X86.492 Y91.026 E1.41449
G1 X85.871 Y91.026 E.02223
G1 X113.819 Y118.974 E1.41449
G1 X113.198 Y118.974 E.02223
M73 P79 R0
G1 X85.25 Y91.026 E1.41449
G1 X84.629 Y91.026 E.02223
G1 X112.576 Y118.974 E1.41449
G1 X111.955 Y118.974 E.02223
M73 P80 R0
G1 X84.008 Y91.026 E1.41449
G1 X83.387 Y91.026 E.02223
G1 X111.334 Y118.974 E1.41449
G1 X110.713 Y118.974 E.02223
M73 P81 R0
G1 X82.766 Y91.026 E1.41449
G1 X82.145 Y91.026 E.02223
G1 X110.092 Y118.974 E1.41449
G1 X109.471 Y118.974 E.02223
M73 P82 R0
G1 X81.524 Y91.026 E1.41449
G1 X81.026 Y91.026 E.0178
G1 X81.026 Y91.15 E.00443
M73 P83 R0
G1 X108.85 Y118.974 E1.40822
G1 X108.229 Y118.974 E.02223
G1 X81.026 Y91.771 E1.37678
G1 X81.026 Y92.392 E.02223
G1 X107.608 Y118.974 E1.34535
M73 P84 R0
G1 X106.986 Y118.974 E.02223
G1 X81.026 Y93.014 E1.31391
G1 X81.026 Y93.635 E.02223
G1 X106.365 Y118.974 E1.28247
G1 X105.744 Y118.974 E.02223
M73 P85 R0
G1 X81.026 Y94.256 E1.25104
G1 X81.026 Y94.877 E.02223
G1 X105.123 Y118.974 E1.2196
G1 X104.502 Y118.974 E.02223
M73 P86 R0
G1 X81.026 Y95.498 E1.18817
G1 X81.026 Y96.119 E.02223
G1 X103.881 Y118.974 E1.15673
G1 X103.26 Y118.974 E.02223
M73 P87 R0
G1 X81.026 Y96.74 E1.12529
G1 X81.026 Y97.361 E.02223
G1 X102.639 Y118.974 E1.09386
G1 X102.018 Y118.974 E.02223
G1 X81.026 Y97.982 E1.06242
M73 P88 R0
G1 X81.026 Y98.604 E.02223
G1 X101.396 Y118.974 E1.03099
G1 X100.775 Y118.974 E.02223
G1 X81.026 Y99.225 E.99955
G1 X81.026 Y99.846 E.02223
M73 P89 R0
G1 X100.154 Y118.974 E.96811
G1 X99.533 Y118.974 E.02223
G1 X81.026 Y100.467 E.93668
G1 X81.026 Y101.088 E.02223
G1 X98.912 Y118.974 E.90524
G1 X98.291 Y118.974 E.02223
M73 P90 R0
G1 X81.026 Y101.709 E.87381
G1 X81.026 Y102.33 E.02223
G1 X97.67 Y118.974 E.84237
G1 X97.049 Y118.974 E.02223
G1 X81.026 Y102.951 E.81093
G1 X81.026 Y103.572 E.02223
M73 P91 R0
G1 X96.428 Y118.974 E.7795
G1 X95.807 Y118.974 E.02223
G1 X81.026 Y104.193 E.74806
G1 X81.026 Y104.815 E.02223
G1 X95.185 Y118.974 E.71663
G1 X94.564 Y118.974 E.02223
M73 P92 R0
G1 X81.026 Y105.436 E.68519
G1 X81.026 Y106.057 E.02223
G1 X93.943 Y118.974 E.65375
G1 X93.322 Y118.974 E.02223
G1 X81.026 Y106.678 E.62232
G1 X81.026 Y107.299 E.02223
G1 X92.701 Y118.974 E.59088
G1 X92.08 Y118.974 E.02223
M73 P93 R0
G1 X81.026 Y107.92 E.55945
G1 X81.026 Y108.541 E.02223
G1 X91.459 Y118.974 E.52801
G1 X90.838 Y118.974 E.02223
G1 X81.026 Y109.162 E.49657
G1 X81.026 Y109.783 E.02223
G1 X90.217 Y118.974 E.46514
G1 X89.595 Y118.974 E.02223
G1 X81.026 Y110.405 E.4337
G1 X81.026 Y111.026 E.02223
M73 P94 R0
G1 X88.974 Y118.974 E.40227
G1 X88.353 Y118.974 E.02223
G1 X81.026 Y111.647 E.37083
G1 X81.026 Y112.268 E.02223
G1 X87.732 Y118.974 E.33939
G1 X87.111 Y118.974 E.02223
G1 X81.026 Y112.889 E.30796
G1 X81.026 Y113.51 E.02223
G1 X86.49 Y118.974 E.27652
G1 X85.869 Y118.974 E.02223
G1 X81.026 Y114.131 E.24509
M73 P95 R0
G1 X81.026 Y114.752 E.02223
G1 X85.248 Y118.974 E.21365
G1 X84.627 Y118.974 E.02223
G1 X81.026 Y115.373 E.18221
G1 X81.026 Y115.995 E.02223
G1 X84.005 Y118.974 E.15078
G1 X83.384 Y118.974 E.02223
G1 X81.026 Y116.616 E.11934
G1 X81.026 Y117.237 E.02223
G1 X82.763 Y118.974 E.08791
G1 X82.142 Y118.974 E.02223
G1 X81.026 Y117.858 E.05647
G1 X81.026 Y118.479 E.02223
G1 X81.718 Y119.17 E.03499
; stop printing object Cube id:106035774743264 copy 0
G1 E-.28 F2100
;WIPE_START
G1 F3600
G1 X81.026 Y118.479 E-.11732
G1 X81.026 Y118.457 E-.00268
;WIPE_END
M106 S0
;TYPE:Custom
; filament end gcode
G1 Z1.2 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z49.2 F720 ; Move print head further up
M73 P97 R0
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 242.75
; filament used [cm3] = 0.58
; filament used [g] = 0.76
; filament cost = 0.02
; total filament used [g] = 0.76
; total filament cost = 0.02
; total layers count = 1
; estimated printing time (normal mode) = 2m 26s
; estimated first layer printing time (normal mode) = 7s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 70
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = /home/jepsu/Documents/Rintteri/_Prusa/mk2_bed.stl
; bed_custom_texture = /home/jepsu/Documents/Rintteri/_Prusa/jose-mk1.png
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 2
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = rectilinear
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 15
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600\nG1 E0.3 F1500 ; prime after color change
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 800
; default_bed_type = 
; default_filament_colour = ""
; default_filament_profile = "Generic PLA @System"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @MyKlipper
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = bottom_shell_layers;bottom_surface_pattern;bridge_acceleration;bridge_speed;brim_type;default_acceleration;enable_overhang_speed;exclude_object;filename_format;gap_infill_speed;initial_layer_acceleration;initial_layer_infill_speed;initial_layer_speed;inner_wall_acceleration;inner_wall_speed;internal_solid_infill_acceleration;internal_solid_infill_speed;outer_wall_acceleration;outer_wall_speed;overhang_2_4_speed;overhang_3_4_speed;overhang_4_4_speed;small_perimeter_speed;sparse_infill_acceleration;sparse_infill_density;sparse_infill_pattern;sparse_infill_speed;top_surface_acceleration;top_surface_speed;travel_acceleration;travel_speed;wall_loops;enable_pressure_advance;filament_max_volumetric_speed;nozzle_temperature;nozzle_temperature_initial_layer;pressure_advance;slow_down_for_layer_cooling;slow_down_layer_time;slow_down_min_speed;bed_custom_model;bed_custom_texture;before_layer_change_gcode;change_filament_gcode;deretraction_speed;machine_end_gcode;machine_max_acceleration_extruding;machine_max_acceleration_retracting;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_jerk_x;machine_max_jerk_y;machine_max_junction_deviation;machine_max_speed_e;machine_pause_gcode;machine_start_gcode;max_layer_height;min_layer_height;print_host;printable_area;printable_height;retraction_length;retraction_speed
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 0
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #26A69A
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #26A69A
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.31
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_flow_ratio = 0.98
; filament_ids = OGFL01
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 200
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PolyTerra PLA @System - Copy"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; Filament gcode\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Polymaker
; filename_format = {input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 40
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 55
; hot_plate_temp_initial_layer = 55
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @MyKlipper";"PolyTerra PLA @System";"MyKlipper 0.4 nozzle"
; initial_layer_acceleration = 800
; initial_layer_infill_speed = 60
; initial_layer_jerk = 9
; initial_layer_line_width = 120%
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 20
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 800
; inner_wall_jerk = 9
; inner_wall_line_width = 110%
; inner_wall_speed = 50
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 2000
; internal_solid_infill_line_width = 120%
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 50
; ironing_angle = -1
; ironing_fan_speed = -1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 110%
; long_retractions_when_cut = 0
; machine_end_gcode = {if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM900 K0 ; reset LA\nM84 ; disable motors
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 10000,20000
; machine_max_acceleration_retracting = 1500,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 9000,20000
; machine_max_acceleration_y = 9000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,9
; machine_max_jerk_y = 10,9
; machine_max_jerk_z = 0.2,0.4
; machine_max_junction_deviation = 1
; machine_max_speed_e = 120,25
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 12,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M601
; machine_start_gcode = M115 U3.2.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM204 S[machine_max_acceleration_extruding] T[machine_max_acceleration_retracting] ; MK2 firmware only supports the old M204 format\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Z0.2 F720\nG1 Y-2 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\nG92 E0
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.25
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.07
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 4
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 230
; nozzle_temperature_initial_layer = 230
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 800
; outer_wall_jerk = 9
; outer_wall_line_width = 100%
; outer_wall_speed = 40
; overhang_1_4_speed = 0
; overhang_2_4_speed = 15
; overhang_3_4_speed = 20
; overhang_4_4_speed = 25
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.0775
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "MyKlipper 0.4 nozzle";"MyKlipper 0.6 nozzle";"MyKlipper 0.8 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @MyJose
; printable_area = 0x0,250x0,250x210,0x210
; printable_height = 200
; printer_model = Generic Klipper Printer
; printer_notes = 
; printer_settings_id = Jose 0.4 nozzle
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.4
; retraction_minimum_travel = 1
; retraction_speed = 35
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 3
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 0
; slow_down_layer_time = 0
; slow_down_layers = 0
; slow_down_min_speed = 0
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 25
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 2000
; sparse_infill_density = 25%
; sparse_infill_filament = 1
; sparse_infill_line_width = 110%
; sparse_infill_pattern = adaptivecubic
; sparse_infill_rotate_template = 
; sparse_infill_speed = 60
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 45
; supertack_plate_temp_initial_layer = 45
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 96%
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 55
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG,300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 4
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 800
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 93.75%
; top_surface_pattern = monotonicline
; top_surface_speed = 40
; travel_acceleration = 1000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 180
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 30
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 55
; bed_shape = 0x0,250x0,250x210,0x210
; first_layer_temperature = 230
; first_layer_height = 0.200
; CONFIG_BLOCK_END


