; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2025-12-21 at 11:54:55
; total layer number: 1
; filament_density: 1.31
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 744
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAB9UlEQVR4Ae2Zy0oCYRzFP8ouKnnNNL
; s4KbSIAjctKijBRRISQ5AQFEktum0EV4EkFBVUOKsCVz5CjzCP0CP4CD7CxFkMTGPm3Ocb+n5wVg7O
; Yf7f+XNGCWEwGAwGzYwE/BHiRSYW5vKZp0Z3SXjsBfOrPPES0fJuM9duSUpNV3iB+mngqc836l9q87
; LwGa4hNBIubtcGGVcKRwrXElrAsUhdnX1qMa9Uun4t+uIxjriJfzlXwBPVa145DdcCjlAaNa7WTPWo
; 41jAhwXVqBwJuNagmjlSuIfl08AXInR2mrct4FMb61WnjKungXsTMyBcbphXCita95GSe4zb5mXBi+
; Z1+1uPoUE4UvA2cBp2rUerhYD3rdtwYauWa7ckr6ivT6EScG/3vVy7JXlB2fcXCZ5/TAFni4atM0yp
; m3NxJBjgBoYYu9dMQbNToZ1NbTUcIUnXLkVajGO5jM8m9fUkHCk0zuzHq6vm4wdlgZgBYVl8uO06bT
; zzfNebzHIFYgWYRuKk0nHKfPLiVCR2EFhb4e0MONaj6QI3jLFkIm/kHVhLUB19R47xe4JV04jtl8wF
; 1ShYt2YCbmlQjSIHXO+6TRwfdghNaO1TCCq1v5X6ImHurz6FKjwaDnGEdlDP1QGPlopN4iXkPmWox9
; CCZ//cYDAYjP/DN62frCx6s5tOAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 3472
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAJ8UlEQVR4Ae3dbW+WZxnA8XsPwCiwtb
; CWQukosIywQFJJbDI0s0aHD4hiIBrhTafLkJGFGpbgFhZmlk03o2iMJr7iI/AR+Ah8hH0EPkLd0ViE
; Cn247uvhPM/r90v+b8y2uHa7c95HzuPcYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQPZe+t6bi9EAIFXPjmwfnbzy67tH/v3XpWj/9ffuPb9n98wA
; ICXbXzsyf+j2Zw9WPqxWiv9tx+zxcwOAFLz8i3O3V39QrS7+mDiBDQC6sG16avbAzev31/uwWin+2P
; hzBgBtiqH6Rj+oVn9FjD/XaQtoXHzQxDC9yofVoxnIA43a9cY3F4b9oFp92oq/5gCgThMLv7pT54fV
; o8Vf21dEYGgxJD/4+c2vmvqwenQg7/oDUNnYT35wq+kPKgN5YCibva5QdzGQd/0BWFfV6wpNnbYGAK
; vF17AmB+vDnLZ8RQQeamuwPsxpy0Ae2NAeYCrZR4Se6nqwXjX7iNAzqQzWq+b6A/TA6gf2cs8+IhTq
; aQ/s5Z59RChMToP1qtlHhMylfl2h7uwjQqZyH6xXzUAeMlLXA3u5ZyAPiav7gb3cs48IiUpxDzCV7C
; NCIvo2WK+afUToWNsP7JWQfURoWa57gKlkHxFa0tfrCnVnIA8NKm0PMJVcf4CalboHmEr2EaEmfdgD
; TCX7iFCR6wrdFAP5ONEOgI0xWO82+4iwAfYA08pAHp7CHmCauf4Aq9gDTL+4UuIrIr1msJ5X8buyj0
; gv2QPMs/iKGL87py16wR5gGcVA3j4iRXNdoawM5ClSfH0wWC831x8ohsF6P/JAINmzB9i/PBBIdgzW
; +50HAsmGwboi+4gkzQN7elIG8iTHA3taKw8EkgyDdW00DwTSGdcVVKUYyLv+QKvsAWqYDORpRQxPXV
; dQXRnI0xgP7KmJ7CNSO3uAaro4bfmKyFAM1tVm9hGpzHUFdZV9RDbMHqBSyD4i67IHqJRy/YEnsgeo
; lHP9gYfsASqH7CNisK7sso/YQ64rKOfsI/aIwbpKyEC+cPGLjeFlTv9QSutlIF8ge4AqOfuIBbEHqL
; 5kHzFjBuvqY/YRM+SBPfU9+4gZsAco/S/7iAlzXUH6/wzkE2MPUFo/1x8SEMdde4DSxjKQ75A9QKla
; BvItMliXhs9AvgUG61J92UdsiMG61FwG8jWKIWFOv3wpxzwQWAN7gFK7eSCwAnuAUnd5IHAT7AFK3W
; cgvw7XFaT0ioG86w+ruK4gpZt9xP+K46bBupRHvX4g0GBdyq9e7iPaA5Tyrhf7iAbrUjkVvY9osC6V
; V3HXH+wBSuVXxD7i9teOzHtgT+pHWe8jGqxL/SyrfUTXFSRlsY9osC5ppWQH8vF/KIZuOf0wJbVTUg
; P5GLLl9MOT1H5J7CPaA5S0mTrZRzRYl1S1VvcRPbAnqY4a3Ue0Byip7hrZR3RdQVJT1TaQtwcoqa2G
; uv4QxzR7gJLaLD5zXjg8Mz/YrK8/6Wb3vf/uV4f/9ees/oYl5dvk1XcebJkYnx9UNfbjt+7MfPlJVn
; /TkvJq5i+fLr04/607gzps2Ts+O/3xBw+ctiTV3dSHi0tDnaqe5LldO2d2n/3hnUN/+zyrH4akNItT
; 1e6f/ejesztGZgZNGXn96EKctnL6wUhKqwMff7C0/eir7ewWxkB+z4Wf3vUVUdJmOvzPL5fGL1249/
; zYaPv/8YoX33zjtoG8pI0UXwF3nZq7PehSnLb2L15x/UHSU9t37bcPah+sDyOuPxjIS3q0lcH6IEUv
; vHronOsPkqIYrG87dHBhkLKHA/l//CmrH66keorB+su//Hk3g/WqYiA//ckN1x+kHnXwi1tLO+dOdj
; tYr8o+otSfkhusV2UfUSq3GKyPnTmd5mC9qm3TU/MG8lJZxWC9iFPVk8RXxNhHNJCX8i4G63vOn212
; DzAVO75xYtE+opRn03/4fXt7gKmI09bk5QUDeSmj4oG9rK4r1M0+opR+tT6wl7s4bU3duGYgLyVYIw
; /slcA+opROSe8BpmJlHzGnX6xUWlnsAabCPqLUTVnuAaYiBvKvfPqR05bUQlnvAabCA4FS8xWzB5gK
; A3mp/gzWG+SBQKm+DNZbYB9RGq5e7QGmYnkf0QOB0qaKPcCR48duDWjf8j7ie78xkJc2UOwBGqwn4K
; Xvfts+ovSU7AEmaMve8dkDH/3OQF56JHuACXtm69bRGMi7/qC+t3JdwWA9A/YR1efiukLvHtjLnX1E
; 9a24rjB+6YI9wJx5IFB9KL4C7jo1Zw+wBPYRVXL2AAtlH1ElZQ+wB+wjqoTsAfaIgbxyzQN7PWYfUT
; kVD+ztmD1hD7DP4rS17/13DeSVdAbrPCYG8q4/KLVisD761vzdAay2bXpq3kBeqRSDdacq1uSBQHVd
; DNbtAbIpywN5+4hquXhgzx4glcRpa+Lti/d9RVQbTSxcvO+6AkOzj6gm88AetYvT1tSNawbyqrX916
; +6rkBz7COqjuwB0hoPBGqY7AHSOvuI2mz2AOlcDOTtI2q9Yg9w59xJD+zRPfuIWit7gCRpeR/x62Fq
; Tv8yqbnin4WxM6cN1kmXfURF9gDJhn3E/haD9T3nz9oDJD/2EftV7AGOHD/mgT3yFaetycsLBvKFN3
; n1HYN1ymEfsczsAVIs+4hlNfXhosE6ZXtm69ZR+4h5t7IHaLBOb9hHzLO4ruCBPXrJPmI+xXWF8UsX
; 7AGCgXzaxVfAXafm7AHCijht7V+84vpDYtkDhDUYyKeRB/Zgg1YG8k5b3eSBPdgkA/n288AeDGl5H9
; EDgY33ymc3l3bMnrAHCMPyQGCz2QOEBiw/EOj6Q23ZA4SGbdk7PmsgP3z2AKElz+3aOeOBwGod+vsf
; 7QFCF0ZeP7pgH3HjxQN79gChQzGQn3j74n1fEdduYuHifdcVIBH2EZ+cPUBIlH3Ex7MHCBno+z6iPU
; DITF/3Ee0BQqb6tI9oDxAKEQP5kvcRD35xa2nn3EmDdShFqfuIButQsFL2EWOwPnbmtME6lG7b9NR8
; zgP5GKw7VUGPxFfE3PYRY7C+5/xZe4DQV8sPBGawjxh7gCPHj3lgD/ouTluTlxeSHcjHA3uuKwCPSW
; 0f0QN7wJritDV141rnA3kP7AEb1tU+oj1AoJKVfcS2PqziuoIH9oDK2thHtAcI1Kqpgbw9QKARdT8Q
; aA8QaNywA3mDdaBVVR8I9MAe0InN7CPaAwSSsLyPuMYDgfYAgaQ87YHA2AM0WAeSNPr97yxff7AHCG
; Rhy97xWacqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAIAy/Af7BvTZwNzYrAAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.44mm
; solid infill extrusion width = 0.48mm
; top infill extrusion width = 0.38mm
; first layer extrusion width = 0.48mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=125,105 POLYGON=[[100,80],[150,80],[150,130],[100,130],[100,80]]
M73 P0 R2
;TYPE:Custom
M115 U3.2.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M204 S10000 T1500 ; MK2 firmware only supports the old M204 format
M104 S220 ; set extruder temp
M140 S55 ; set bed temp
M190 S55 ; wait for bed temp
M109 S220 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Z0.2 F720
G1 Y-2 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
M73 P2 R2
G92 E0
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2

G1 E-.4 F2100
M73 P4 R2
;AFTER_LAYER_CHANGE
;0.2
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=800 ACCEL_TO_DECEL=400
; printing object Cube id:0 copy 0
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 Z.6 F10800
G1 X148.864 Y128.864
G1 Z.6
M73 P5 R2
G1 Z.2
G1 E.4 F2100
;TYPE:Inner wall
;WIDTH:0.479999
G1 F1200
G1 X101.136 Y128.864 E1.69993
G1 X101.136 Y81.136 E1.69993
M73 P6 R2
G1 X148.864 Y81.136 E1.69993
M73 P8 R2
G1 X148.864 Y128.824 E1.6985
M73 P10 R2
G1 X149.301 Y129.301 F10800
M73 P12 R2
G1 F1200
G1 X100.699 Y129.301 E1.73106
G1 X100.699 Y80.699 E1.73106
M73 P13 R2
G1 X149.301 Y80.699 E1.73106
M73 P15 R1
G1 X149.301 Y129.261 E1.72964
M73 P17 R1
G1 X149.76 Y129.76 F10800
M73 P19 R1
;TYPE:Outer wall
G1 F1200
G1 X100.24 Y129.76 E1.76372
G1 X100.24 Y80.24 E1.76372
M73 P20 R1
G1 X149.76 Y80.24 E1.76372
M73 P22 R1
G1 X149.76 Y129.72 E1.7623
M73 P24 R1
G1 E-.28 F2100
M73 P26 R1
;WIPE_START
G1 F1200
G1 X148.76 Y129.721 E-.12
;WIPE_END
G1 Z.6 F10800
G1 X148.733 Y82.155 Z.6
G1 Z.2
G1 E.4 F2100
;TYPE:Bottom surface
;WIDTH:0.482067
G1 F3600
G1 X148.042 Y81.463 E.03498
G1 X147.421 Y81.463 E.02222
G1 X148.537 Y82.579 E.05646
G1 X148.537 Y83.2 E.02222
G1 X146.8 Y81.463 E.08789
G1 X146.179 Y81.463 E.02222
G1 X148.537 Y83.821 E.11932
G1 X148.537 Y84.442 E.02222
G1 X145.558 Y81.463 E.15075
G1 X144.937 Y81.463 E.02222
M73 P27 R1
G1 X148.537 Y85.063 E.18218
G1 X148.537 Y85.684 E.02222
G1 X144.316 Y81.463 E.21361
G1 X143.695 Y81.463 E.02222
G1 X148.537 Y86.305 E.24504
G1 X148.537 Y86.926 E.02222
G1 X143.074 Y81.463 E.27647
G1 X142.453 Y81.463 E.02222
G1 X148.537 Y87.547 E.3079
G1 X148.537 Y88.168 E.02222
G1 X141.832 Y81.463 E.33933
G1 X141.21 Y81.463 E.02222
G1 X148.537 Y88.79 E.37076
G1 X148.537 Y89.411 E.02222
M73 P28 R1
G1 X140.589 Y81.463 E.40218
G1 X139.968 Y81.463 E.02222
G1 X148.537 Y90.032 E.43361
G1 X148.537 Y90.653 E.02222
G1 X139.347 Y81.463 E.46504
G1 X138.726 Y81.463 E.02222
G1 X148.537 Y91.274 E.49647
G1 X148.537 Y91.895 E.02222
G1 X138.105 Y81.463 E.5279
G1 X137.484 Y81.463 E.02222
M73 P29 R1
G1 X148.537 Y92.516 E.55933
G1 X148.537 Y93.137 E.02222
G1 X136.863 Y81.463 E.59076
G1 X136.242 Y81.463 E.02222
G1 X148.537 Y93.758 E.62219
G1 X148.537 Y94.379 E.02222
G1 X135.621 Y81.463 E.65362
G1 X135 Y81.463 E.02222
M73 P30 R1
G1 X148.537 Y95 E.68505
G1 X148.537 Y95.621 E.02222
G1 X134.379 Y81.463 E.71648
G1 X133.758 Y81.463 E.02222
G1 X148.537 Y96.242 E.74791
G1 X148.537 Y96.863 E.02222
M73 P31 R1
G1 X133.137 Y81.463 E.77934
G1 X132.516 Y81.463 E.02222
G1 X148.537 Y97.484 E.81077
G1 X148.537 Y98.105 E.02222
G1 X131.895 Y81.463 E.8422
G1 X131.274 Y81.463 E.02222
M73 P32 R1
G1 X148.537 Y98.726 E.87363
G1 X148.537 Y99.347 E.02222
G1 X130.653 Y81.463 E.90506
G1 X130.032 Y81.463 E.02222
G1 X148.537 Y99.968 E.93649
G1 X148.537 Y100.589 E.02222
M73 P33 R1
G1 X129.411 Y81.463 E.96792
G1 X128.79 Y81.463 E.02222
G1 X148.537 Y101.21 E.99935
G1 X148.537 Y101.832 E.02222
G1 X128.168 Y81.463 E1.03078
G1 X127.547 Y81.463 E.02222
M73 P34 R1
G1 X148.537 Y102.453 E1.06221
G1 X148.537 Y103.074 E.02222
G1 X126.926 Y81.463 E1.09364
G1 X126.305 Y81.463 E.02222
M73 P35 R1
G1 X148.537 Y103.695 E1.12507
G1 X148.537 Y104.316 E.02222
G1 X125.684 Y81.463 E1.1565
G1 X125.063 Y81.463 E.02222
M73 P36 R1
G1 X148.537 Y104.937 E1.18793
G1 X148.537 Y105.558 E.02222
G1 X124.442 Y81.463 E1.21936
G1 X123.821 Y81.463 E.02222
G1 X148.537 Y106.179 E1.25079
G1 X148.537 Y106.8 E.02222
M73 P37 R1
G1 X123.2 Y81.463 E1.28222
G1 X122.579 Y81.463 E.02222
G1 X148.537 Y107.421 E1.31365
G1 X148.537 Y108.042 E.02222
M73 P38 R1
G1 X121.958 Y81.463 E1.34507
G1 X121.337 Y81.463 E.02222
G1 X148.537 Y108.663 E1.3765
G1 X148.537 Y109.284 E.02222
M73 P39 R1
G1 X120.716 Y81.463 E1.40793
G1 X120.095 Y81.463 E.02222
G1 X148.537 Y109.905 E1.43936
G1 X148.537 Y110.526 E.02222
M73 P40 R1
G1 X119.474 Y81.463 E1.47079
G1 X118.853 Y81.463 E.02222
M73 P41 R1
G1 X148.537 Y111.147 E1.50222
G1 X148.537 Y111.768 E.02222
G1 X118.232 Y81.463 E1.53365
G1 X117.611 Y81.463 E.02222
M73 P42 R1
G1 X148.537 Y112.389 E1.56508
G1 X148.537 Y113.01 E.02222
G1 X116.99 Y81.463 E1.59651
G1 X116.369 Y81.463 E.02222
M73 P43 R1
G1 X148.537 Y113.631 E1.62794
G1 X148.537 Y114.252 E.02222
G1 X115.748 Y81.463 E1.65937
G1 X115.126 Y81.463 E.02222
M73 P44 R1
G1 X148.537 Y114.874 E1.6908
G1 X148.537 Y115.495 E.02222
M73 P45 R1
G1 X114.505 Y81.463 E1.72223
G1 X113.884 Y81.463 E.02222
G1 X148.537 Y116.116 E1.75366
G1 X148.537 Y116.737 E.02222
M73 P46 R1
G1 X113.263 Y81.463 E1.78509
G1 X112.642 Y81.463 E.02222
M73 P47 R1
G1 X148.537 Y117.358 E1.81652
G1 X148.537 Y117.979 E.02222
G1 X112.021 Y81.463 E1.84795
G1 X111.4 Y81.463 E.02222
M73 P48 R1
G1 X148.537 Y118.6 E1.87938
G1 X148.537 Y119.221 E.02222
M73 P49 R1
G1 X110.779 Y81.463 E1.91081
G1 X110.158 Y81.463 E.02222
G1 X148.537 Y119.842 E1.94224
G1 X148.537 Y120.463 E.02222
M73 P50 R1
G1 X109.537 Y81.463 E1.97367
G1 X108.916 Y81.463 E.02222
M73 P51 R1
G1 X148.537 Y121.084 E2.0051
G1 X148.537 Y121.705 E.02222
G1 X108.295 Y81.463 E2.03653
G1 X107.674 Y81.463 E.02222
M73 P52 R1
G1 X148.537 Y122.326 E2.06796
G1 X148.537 Y122.947 E.02222
M73 P53 R1
G1 X107.053 Y81.463 E2.09939
G1 X106.432 Y81.463 E.02222
M73 P54 R1
G1 X148.537 Y123.568 E2.13082
G1 X148.537 Y124.189 E.02222
G1 X105.811 Y81.463 E2.16225
G1 X105.19 Y81.463 E.02222
M73 P55 R1
G1 X148.537 Y124.81 E2.19368
G1 X148.537 Y125.431 E.02222
M73 P56 R1
G1 X104.569 Y81.463 E2.22511
G1 X103.948 Y81.463 E.02222
M73 P57 R1
G1 X148.537 Y126.052 E2.25654
G1 X148.537 Y126.673 E.02222
M73 P58 R0
G1 X103.327 Y81.463 E2.28797
G1 X102.706 Y81.463 E.02222
G1 X148.537 Y127.294 E2.31939
G1 X148.537 Y127.916 E.02222
M73 P59 R0
G1 X102.084 Y81.463 E2.35082
G1 X101.463 Y81.463 E.02222
M73 P60 R0
G1 X148.537 Y128.537 E2.38225
G1 X147.916 Y128.537 E.02222
M73 P61 R0
G1 X101.463 Y82.084 E2.35083
G1 X101.463 Y82.706 E.02222
M73 P62 R0
G1 X147.294 Y128.537 E2.3194
G1 X146.673 Y128.537 E.02222
M73 P63 R0
G1 X101.463 Y83.327 E2.28797
G1 X101.463 Y83.948 E.02222
G1 X146.052 Y128.537 E2.25654
G1 X145.431 Y128.537 E.02222
M73 P64 R0
G1 X101.463 Y84.569 E2.22511
G1 X101.463 Y85.19 E.02222
M73 P65 R0
G1 X144.81 Y128.537 E2.19368
G1 X144.189 Y128.537 E.02222
M73 P66 R0
G1 X101.463 Y85.811 E2.16225
G1 X101.463 Y86.432 E.02222
M73 P67 R0
G1 X143.568 Y128.537 E2.13082
G1 X142.947 Y128.537 E.02222
G1 X101.463 Y87.053 E2.09939
G1 X101.463 Y87.674 E.02222
M73 P68 R0
G1 X142.326 Y128.537 E2.06796
G1 X141.705 Y128.537 E.02222
M73 P69 R0
G1 X101.463 Y88.295 E2.03653
G1 X101.463 Y88.916 E.02222
M73 P70 R0
G1 X141.084 Y128.537 E2.0051
G1 X140.463 Y128.537 E.02222
G1 X101.463 Y89.537 E1.97367
G1 X101.463 Y90.158 E.02222
M73 P71 R0
G1 X139.842 Y128.537 E1.94224
G1 X139.221 Y128.537 E.02222
M73 P72 R0
G1 X101.463 Y90.779 E1.91081
G1 X101.463 Y91.4 E.02222
G1 X138.6 Y128.537 E1.87938
M73 P73 R0
G1 X137.979 Y128.537 E.02222
G1 X101.463 Y92.021 E1.84795
G1 X101.463 Y92.642 E.02222
M73 P74 R0
G1 X137.358 Y128.537 E1.81652
G1 X136.737 Y128.537 E.02222
M73 P75 R0
G1 X101.463 Y93.263 E1.78509
G1 X101.463 Y93.884 E.02222
G1 X136.116 Y128.537 E1.75366
G1 X135.495 Y128.537 E.02222
M73 P76 R0
G1 X101.463 Y94.505 E1.72223
G1 X101.463 Y95.126 E.02222
G1 X134.874 Y128.537 E1.6908
G1 X134.252 Y128.537 E.02222
M73 P77 R0
G1 X101.463 Y95.748 E1.65937
G1 X101.463 Y96.369 E.02222
M73 P78 R0
G1 X133.631 Y128.537 E1.62794
G1 X133.01 Y128.537 E.02222
G1 X101.463 Y96.99 E1.59651
G1 X101.463 Y97.611 E.02222
M73 P79 R0
G1 X132.389 Y128.537 E1.56508
G1 X131.768 Y128.537 E.02222
G1 X101.463 Y98.232 E1.53365
G1 X101.463 Y98.853 E.02222
M73 P80 R0
G1 X131.147 Y128.537 E1.50222
G1 X130.526 Y128.537 E.02222
M73 P81 R0
G1 X101.463 Y99.474 E1.47079
G1 X101.463 Y100.095 E.02222
G1 X129.905 Y128.537 E1.43937
G1 X129.284 Y128.537 E.02222
M73 P82 R0
G1 X101.463 Y100.716 E1.40794
G1 X101.463 Y101.337 E.02222
G1 X128.663 Y128.537 E1.37651
G1 X128.042 Y128.537 E.02222
M73 P83 R0
G1 X101.463 Y101.958 E1.34508
G1 X101.463 Y102.579 E.02222
G1 X127.421 Y128.537 E1.31365
G1 X126.8 Y128.537 E.02222
M73 P84 R0
G1 X101.463 Y103.2 E1.28222
G1 X101.463 Y103.821 E.02222
G1 X126.179 Y128.537 E1.25079
G1 X125.558 Y128.537 E.02222
M73 P85 R0
G1 X101.463 Y104.442 E1.21936
G1 X101.463 Y105.063 E.02222
G1 X124.937 Y128.537 E1.18793
G1 X124.316 Y128.537 E.02222
M73 P86 R0
G1 X101.463 Y105.684 E1.1565
G1 X101.463 Y106.305 E.02222
G1 X123.695 Y128.537 E1.12507
G1 X123.074 Y128.537 E.02222
G1 X101.463 Y106.926 E1.09364
G1 X101.463 Y107.547 E.02222
M73 P87 R0
G1 X122.453 Y128.537 E1.06221
G1 X121.832 Y128.537 E.02222
G1 X101.463 Y108.168 E1.03078
G1 X101.463 Y108.79 E.02222
M73 P88 R0
G1 X121.21 Y128.537 E.99935
G1 X120.589 Y128.537 E.02222
G1 X101.463 Y109.411 E.96792
G1 X101.463 Y110.032 E.02222
G1 X119.968 Y128.537 E.93649
G1 X119.347 Y128.537 E.02222
M73 P89 R0
G1 X101.463 Y110.653 E.90506
G1 X101.463 Y111.274 E.02222
G1 X118.726 Y128.537 E.87363
G1 X118.105 Y128.537 E.02222
M73 P90 R0
G1 X101.463 Y111.895 E.8422
G1 X101.463 Y112.516 E.02222
G1 X117.484 Y128.537 E.81077
G1 X116.863 Y128.537 E.02222
G1 X101.463 Y113.137 E.77934
G1 X101.463 Y113.758 E.02222
M73 P91 R0
G1 X116.242 Y128.537 E.74791
G1 X115.621 Y128.537 E.02222
G1 X101.463 Y114.379 E.71648
G1 X101.463 Y115 E.02222
G1 X115 Y128.537 E.68505
G1 X114.379 Y128.537 E.02222
G1 X101.463 Y115.621 E.65362
G1 X101.463 Y116.242 E.02222
M73 P92 R0
G1 X113.758 Y128.537 E.62219
G1 X113.137 Y128.537 E.02222
G1 X101.463 Y116.863 E.59076
G1 X101.463 Y117.484 E.02222
G1 X112.516 Y128.537 E.55933
G1 X111.895 Y128.537 E.02222
G1 X101.463 Y118.105 E.5279
G1 X101.463 Y118.726 E.02222
M73 P93 R0
G1 X111.274 Y128.537 E.49647
G1 X110.653 Y128.537 E.02222
G1 X101.463 Y119.347 E.46505
G1 X101.463 Y119.968 E.02222
G1 X110.032 Y128.537 E.43362
G1 X109.411 Y128.537 E.02222
G1 X101.463 Y120.589 E.40219
G1 X101.463 Y121.21 E.02222
G1 X108.79 Y128.537 E.37076
M73 P94 R0
G1 X108.168 Y128.537 E.02222
G1 X101.463 Y121.832 E.33933
G1 X101.463 Y122.453 E.02222
G1 X107.547 Y128.537 E.3079
G1 X106.926 Y128.537 E.02222
G1 X101.463 Y123.074 E.27647
G1 X101.463 Y123.695 E.02222
G1 X106.305 Y128.537 E.24504
G1 X105.684 Y128.537 E.02222
G1 X101.463 Y124.316 E.21361
G1 X101.463 Y124.937 E.02222
G1 X105.063 Y128.537 E.18218
G1 X104.442 Y128.537 E.02222
M73 P95 R0
G1 X101.463 Y125.558 E.15075
G1 X101.463 Y126.179 E.02222
G1 X103.821 Y128.537 E.11932
G1 X103.2 Y128.537 E.02222
G1 X101.463 Y126.8 E.08789
G1 X101.463 Y127.421 E.02222
G1 X102.579 Y128.537 E.05646
G1 X101.958 Y128.537 E.02222
G1 X101.267 Y127.845 E.03498
; stop printing object Cube id:0 copy 0
G1 E-.28 F2100
;WIPE_START
G1 F3600
G1 X101.958 Y128.537 E-.11731
G1 X101.98 Y128.537 E-.00269
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode
G1 Z1.2 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z49.2 F720 ; Move print head further up
M73 P97 R0
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 226.20
; filament used [cm3] = 0.54
; filament used [g] = 0.71
; filament cost = 0.02
; total filament used [g] = 0.71
; total filament cost = 0.02
; total layers count = 1
; estimated printing time (normal mode) = 2m 20s
; estimated first layer printing time (normal mode) = 7s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 70
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 15
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600\nG1 E0.3 F1500 ; prime after color change
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 800
; default_bed_type = 
; default_filament_colour = ""
; default_filament_profile = "Generic PLA @System"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @MyKlipper
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = bridge_acceleration;bridge_speed;brim_type;default_acceleration;gap_infill_speed;initial_layer_acceleration;initial_layer_infill_speed;initial_layer_speed;inner_wall_acceleration;inner_wall_speed;internal_solid_infill_acceleration;internal_solid_infill_speed;outer_wall_acceleration;outer_wall_speed;overhang_2_4_speed;overhang_3_4_speed;overhang_4_4_speed;small_perimeter_speed;sparse_infill_acceleration;sparse_infill_pattern;sparse_infill_speed;top_surface_acceleration;top_surface_speed;travel_acceleration;travel_speed;;before_layer_change_gcode;change_filament_gcode;deretraction_speed;machine_end_gcode;machine_max_acceleration_extruding;machine_max_acceleration_retracting;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_jerk_x;machine_max_jerk_y;machine_max_speed_e;machine_pause_gcode;machine_start_gcode;max_layer_height;min_layer_height;print_host;printable_area;printable_height;retraction_length;retraction_speed
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #26A69A
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #26A69A
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.31
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_flow_ratio = 0.98
; filament_ids = OGFL01
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 22
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PolyTerra PLA @System"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; Filament gcode\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Polymaker
; filename_format = {input_filename_base}_{layer_height}mm_{filament_type[initial_tool]}_{printer_model}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_target = nowhere
; gap_infill_speed = 40
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 55
; hot_plate_temp_initial_layer = 55
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @MyKlipper";;"MyKlipper 0.4 nozzle"
; initial_layer_acceleration = 800
; initial_layer_infill_speed = 60
; initial_layer_jerk = 9
; initial_layer_line_width = 120%
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 20
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 800
; inner_wall_jerk = 9
; inner_wall_line_width = 110%
; inner_wall_speed = 50
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 2000
; internal_solid_infill_line_width = 120%
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 50
; ironing_angle = -1
; ironing_fan_speed = -1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 110%
; long_retractions_when_cut = 0
; machine_end_gcode = {if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM900 K0 ; reset LA\nM84 ; disable motors
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 10000,20000
; machine_max_acceleration_retracting = 1500,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 9000,20000
; machine_max_acceleration_y = 9000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,9
; machine_max_jerk_y = 10,9
; machine_max_jerk_z = 0.2,0.4
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 120,25
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 12,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = M601
; machine_start_gcode = M115 U3.2.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM204 S[machine_max_acceleration_extruding] T[machine_max_acceleration_retracting] ; MK2 firmware only supports the old M204 format\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Z0.2 F720\nG1 Y-2 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\nG92 E0
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.25
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.07
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 4
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 800
; outer_wall_jerk = 9
; outer_wall_line_width = 100%
; outer_wall_speed = 40
; overhang_1_4_speed = 0
; overhang_2_4_speed = 15
; overhang_3_4_speed = 20
; overhang_4_4_speed = 25
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "MyKlipper 0.4 nozzle";"MyKlipper 0.6 nozzle";"MyKlipper 0.8 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @MyJose
; printable_area = 0x0,250x0,250x210,0x210
; printable_height = 200
; printer_model = Generic Klipper Printer
; printer_notes = 
; printer_settings_id = Jose 0.4 nozzle
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.4
; retraction_minimum_travel = 1
; retraction_speed = 35
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 3
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 4
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 25
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 2000
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_line_width = 110%
; sparse_infill_pattern = adaptivecubic
; sparse_infill_rotate_template = 
; sparse_infill_speed = 60
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 45
; supertack_plate_temp_initial_layer = 45
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 96%
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 55
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG,300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 4
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 800
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 93.75%
; top_surface_pattern = monotonicline
; top_surface_speed = 40
; travel_acceleration = 1000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 180
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 30
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 3
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 55
; bed_shape = 0x0,250x0,250x210,0x210
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END


