M118 E1 OCTOAPP_DISABLE_LAYER_MAXIC
; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2025-10-26 at 11:03:36
; total layer number: 1
; filament_density: 1.31
; filament_diameter: 1.75
; max_z_height: 0.20
; HEADER_BLOCK_END
; THUMBNAIL_BLOCK_START
;
; thumbnail begin 48x48 192
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAVklEQVR4Ae3PsQ1AABRF0dcpqXQSAy
; gUOgNpNbQGNgQ7SL7qnOQOcBMAAOBPU5+5oqHNmGrbkv0+81R0rLlSzYABAwYMGDBgwIABA5+1Tbqq
; AgAA/OkFulV1UPwV4MkAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END
; THUMBNAIL_BLOCK_START
;
; thumbnail begin 300x300 1280
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAADhklEQVR4Ae3UMU0eYABF0U9Xt9ZBhy
; Z1UAFNEEDYkUDCxgQOcAASEIAICCPj/4Y7nZNcBy/vHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD47ubXuX35d96kS7v/fR4PlL5G9351PqRLe/p7
; ng+UHJbWHBY5h6U1h0XOYWnNYZFzWFpzWOQcltYcFjmHpTWHRc5hac1hkXNYWnNY5ByW1hwWOYelNY
; dFzmFpzWGRc1hac1jkHJbWHBY5h6U1h0XOYWnNYZFzWFpzWOQcltYcFjmHpTWHRc5hac1hkXNYWnNY
; 5ByW1hwWOYelNYdFzmFpzWGRc1hac1jkHJbWHBY5h6U1h0XOYWnNYZFzWFpzWOQcltYcFjmHpTWHRc
; 5hac1hkXNYWnNY5ByW1hwWOYelNYdFzmFpzWGRc1hac1jkHJbWHBY5h6U1h0XOYWnNYZFzWFpzWOQc
; ltYcFjmHpTWHRc5hac1hkXNYWnNY5ByW1hwWOYelNYdFzmFpzWGRc1hac1jkHJbWHBY5h6U1h0XOYW
; nNYZFzWFpzWOQcltYcFjmHpTWHRc5hac1hkXNYWnNY5ByW1hwWOYelNYdFzmFpzWGRc1hac1jkHJbW
; HBY5h6U1h0XOYWnNYZFzWFpzWOQcltYcFjmHpTWHRc5hac1hkXNYWnNY5ByW1hwWOYelNYdFzmFpzW
; GRc1hac1jkHJbWHBY5h6U1h0XOYWnNYZFzWFpzWOQcltYcFjmHpTWHRc5hac1hkXNYWnNY5ByW1hwW
; OYelNYdFzmFpzWGRc1hac1jkHJbWHBY5h6U1h0XOYWnNYZFzWFpzWOQcltYcFjmHpTWHRc5hac1hkX
; NYWnNY5ByW1hwWOYelNYdFzmFpzWGRc1hac1jkHJbWHBY5h6U1h0XOYWnNYZG7/nnuHv6cV+nS/v84
; twcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; vvsEfslGUR0et6IAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; EXECUTABLE_BLOCK_START
M73 P0 R8
M201 X1000 Y1000 Z200 E800
M203 X200 Y200 Z12 E120
M204 P1250 R1000 T1250
M205 X10.00 Y10.00 Z0.40 E5.00 ; sets the jerk limits, mm/sec
;TYPE:Custom
M862.3 P "" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.2.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M204 S1250 T1000 ; MK2 firmware only supports the old M204 format
M104 S220 ; set extruder temp
M140 S55 ; set bed temp
M190 S55 ; wait for bed temp
M109 S220 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Z2.0 F3000 ;Move Z Axis up
G1 X42.3119 Y32.3119 Z0.8 F5000 ; Move to start
M109 S220 ; wait for nozzle temp to stabilize
G92 E0 ;Reset Extruder
G1 X42.3119 Y62.3119 E30 F360.0 ; Extrude 30mm in Y
G92 E0 ;Reset Extruder
G1 E-0.5 F2100 ; Retract
M73 P1 R8
G1 Y72.3119 F5000 ; Move 10mm in Y
G92 E0  ;Reset Extrude
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
M106 S0
;LAYER_CHANGE
M117 DASHBOARD_LAYER_INDICATOR 1
M118 E1 OCTOAPP_LAYER LAYER=0
M117 DASHBOARD_LAYER_INDICATOR 1
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2
G1 E-.8 F1800
;_SET_FAN_SPEED_CHANGING_LAYER
M204 S300
; printing object Cube id:15 copy 0
G1 X125 Y174.504 F7200
G1 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Inner wall
;WIDTH:0.449999
G1 F1200
G1 X55.496 Y105 E3.19401
G1 X125 Y35.496 E3.19401
M73 P2 R8
G1 X194.504 Y105 E3.19401
M73 P3 R8
G1 X125.028 Y174.475 E3.19271
M73 P4 R7
G1 X125 Y175.11 F7200
M73 P5 R7
;TYPE:Outer wall
G1 F1200
G1 X54.89 Y105 E3.22186
G1 X125 Y34.89 E3.22186
M73 P6 R7
G1 X195.11 Y105 E3.22186
M73 P7 R7
G1 X125.028 Y175.081 E3.22056
M73 P8 R7
G1 E-.08 F1800
M73 P9 R7
;WIPE_START
G1 F1200
G1 X124.321 Y174.375 E-.72
;WIPE_END
G1 X124.326 Y166.742 Z.6 F7200
G1 X124.417 Y36.252 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Bottom surface
;WIDTH:0.450918
G1 F3600
G1 X125.324 Y36.252 E.02955
G1 X125.732 Y36.66 E.01879
G1 X124.268 Y36.66 E.04769
G1 X123.86 Y37.068 E.01879
G1 X126.14 Y37.068 E.07427
G1 X126.548 Y37.476 E.01879
G1 X123.452 Y37.476 E.10084
G1 X123.044 Y37.884 E.01879
G1 X126.956 Y37.884 E.12742
G1 X127.364 Y38.292 E.01879
G1 X122.636 Y38.292 E.15399
M73 P10 R7
G1 X122.228 Y38.7 E.01879
G1 X127.772 Y38.7 E.18057
G1 X128.18 Y39.108 E.01879
G1 X121.82 Y39.108 E.20715
G1 X121.412 Y39.516 E.01879
G1 X128.588 Y39.516 E.23372
G1 X128.996 Y39.924 E.01879
G1 X121.004 Y39.924 E.2603
G1 X120.596 Y40.332 E.01879
G1 X129.404 Y40.332 E.28687
G1 X129.812 Y40.74 E.01879
G1 X120.188 Y40.74 E.31345
G1 X119.78 Y41.148 E.01879
G1 X130.22 Y41.148 E.34002
G1 X130.628 Y41.556 E.01879
G1 X119.372 Y41.556 E.3666
G1 X118.964 Y41.964 E.01879
G1 X131.036 Y41.964 E.39317
G1 X131.444 Y42.372 E.01879
G1 X118.556 Y42.372 E.41975
G1 X118.148 Y42.78 E.01879
G1 X131.852 Y42.78 E.44632
G1 X132.26 Y43.188 E.01879
G1 X117.74 Y43.188 E.4729
G1 X117.332 Y43.596 E.01879
G1 X132.668 Y43.596 E.49948
G1 X133.076 Y44.004 E.01879
G1 X116.924 Y44.004 E.52605
G1 X116.516 Y44.412 E.01879
M73 P11 R7
G1 X133.484 Y44.412 E.55263
G1 X133.892 Y44.82 E.01879
G1 X116.108 Y44.82 E.5792
G1 X115.7 Y45.228 E.01879
G1 X134.3 Y45.228 E.60578
G1 X134.708 Y45.636 E.01879
G1 X115.292 Y45.636 E.63235
G1 X114.884 Y46.044 E.01879
G1 X135.116 Y46.044 E.65893
G1 X135.524 Y46.452 E.01879
G1 X114.476 Y46.452 E.6855
G1 X114.068 Y46.86 E.01879
G1 X135.932 Y46.86 E.71208
G1 X136.34 Y47.268 E.01879
G1 X113.66 Y47.268 E.73866
G1 X113.252 Y47.676 E.01879
G1 X136.748 Y47.676 E.76523
G1 X137.156 Y48.084 E.01879
G1 X112.844 Y48.084 E.79181
G1 X112.436 Y48.492 E.01879
M73 P12 R7
G1 X137.564 Y48.492 E.81838
G1 X137.972 Y48.9 E.01879
G1 X112.028 Y48.9 E.84496
G1 X111.62 Y49.308 E.01879
G1 X138.38 Y49.308 E.87153
G1 X138.788 Y49.716 E.01879
G1 X111.212 Y49.716 E.89811
G1 X110.804 Y50.124 E.01879
G1 X139.196 Y50.124 E.92468
G1 X139.604 Y50.532 E.01879
G1 X110.396 Y50.532 E.95126
G1 X109.988 Y50.94 E.01879
G1 X140.012 Y50.94 E.97783
G1 X140.42 Y51.348 E.01879
G1 X109.58 Y51.348 E1.00441
G1 X109.172 Y51.756 E.01879
M73 P13 R7
G1 X140.828 Y51.756 E1.03099
G1 X141.236 Y52.164 E.01879
G1 X108.764 Y52.164 E1.05756
G1 X108.356 Y52.572 E.01879
G1 X141.644 Y52.572 E1.08414
G1 X142.052 Y52.98 E.01879
G1 X107.948 Y52.98 E1.11071
G1 X107.54 Y53.388 E.01879
G1 X142.46 Y53.388 E1.13729
G1 X142.868 Y53.796 E.01879
G1 X107.132 Y53.796 E1.16386
G1 X106.724 Y54.204 E.01879
G1 X143.276 Y54.204 E1.19044
G1 X143.684 Y54.612 E.01879
M73 P14 R7
G1 X106.316 Y54.612 E1.21701
G1 X105.908 Y55.02 E.01879
G1 X144.092 Y55.02 E1.24359
G1 X144.5 Y55.428 E.01879
G1 X105.5 Y55.428 E1.27017
G1 X105.092 Y55.836 E.01879
G1 X144.908 Y55.836 E1.29674
G1 X145.316 Y56.244 E.01879
G1 X104.684 Y56.244 E1.32332
G1 X104.276 Y56.652 E.01879
G1 X145.724 Y56.652 E1.34989
G1 X146.132 Y57.06 E.01879
M73 P15 R7
G1 X103.868 Y57.06 E1.37647
G1 X103.46 Y57.468 E.01879
G1 X146.54 Y57.468 E1.40304
G1 X146.948 Y57.876 E.01879
G1 X103.052 Y57.876 E1.42962
G1 X102.644 Y58.284 E.01879
G1 X147.356 Y58.284 E1.45619
G1 X147.764 Y58.692 E.01879
G1 X102.236 Y58.692 E1.48277
G1 X101.828 Y59.1 E.01879
G1 X148.172 Y59.1 E1.50934
G1 X148.58 Y59.508 E.01879
M73 P16 R7
G1 X101.42 Y59.508 E1.53592
G1 X101.012 Y59.916 E.01879
G1 X148.988 Y59.916 E1.5625
G1 X149.396 Y60.324 E.01879
M73 P16 R6
G1 X100.604 Y60.324 E1.58907
G1 X100.196 Y60.732 E.01879
G1 X149.804 Y60.732 E1.61565
G1 X150.212 Y61.14 E.01879
G1 X99.788 Y61.14 E1.64222
G1 X99.38 Y61.548 E.01879
M73 P17 R6
G1 X150.62 Y61.548 E1.6688
G1 X151.028 Y61.956 E.01879
G1 X98.972 Y61.956 E1.69537
G1 X98.564 Y62.364 E.01879
G1 X151.436 Y62.364 E1.72195
G1 X151.844 Y62.772 E.01879
G1 X98.156 Y62.772 E1.74852
G1 X97.748 Y63.18 E.01879
G1 X152.252 Y63.18 E1.7751
G1 X152.66 Y63.588 E.01879
M73 P18 R6
G1 X97.34 Y63.588 E1.80167
G1 X96.932 Y63.996 E.01879
G1 X153.068 Y63.996 E1.82825
G1 X153.476 Y64.404 E.01879
G1 X96.524 Y64.404 E1.85483
G1 X96.116 Y64.812 E.01879
G1 X153.884 Y64.812 E1.8814
G1 X154.292 Y65.22 E.01879
M73 P19 R6
G1 X95.708 Y65.22 E1.90798
G1 X95.3 Y65.628 E.01879
G1 X154.7 Y65.628 E1.93455
G1 X155.108 Y66.036 E.01879
G1 X94.892 Y66.036 E1.96113
G1 X94.484 Y66.444 E.01879
G1 X155.516 Y66.444 E1.9877
G1 X155.924 Y66.852 E.01879
G1 X94.076 Y66.852 E2.01428
G1 X93.668 Y67.26 E.01879
M73 P20 R6
G1 X156.332 Y67.26 E2.04085
G1 X156.74 Y67.668 E.01879
G1 X93.26 Y67.668 E2.06743
G1 X92.852 Y68.076 E.01879
G1 X157.148 Y68.076 E2.09401
G1 X157.556 Y68.484 E.01879
G1 X92.444 Y68.484 E2.12058
G1 X92.036 Y68.892 E.01879
M73 P21 R6
G1 X157.964 Y68.892 E2.14716
G1 X158.372 Y69.3 E.01879
G1 X91.628 Y69.3 E2.17373
G1 X91.22 Y69.708 E.01879
G1 X158.78 Y69.708 E2.20031
G1 X159.188 Y70.116 E.01879
G1 X90.812 Y70.116 E2.22688
G1 X90.404 Y70.524 E.01879
M73 P22 R6
G1 X159.596 Y70.524 E2.25346
G1 X160.004 Y70.932 E.01879
G1 X89.996 Y70.932 E2.28003
G1 X89.588 Y71.34 E.01879
G1 X160.412 Y71.34 E2.30661
G1 X160.82 Y71.748 E.01879
M73 P23 R6
G1 X89.18 Y71.748 E2.33318
G1 X88.772 Y72.156 E.01879
G1 X161.228 Y72.156 E2.35976
G1 X161.636 Y72.564 E.01879
G1 X88.364 Y72.564 E2.38634
G1 X87.956 Y72.972 E.01879
G1 X162.044 Y72.972 E2.41291
G1 X162.452 Y73.38 E.01879
M73 P24 R6
G1 X87.548 Y73.38 E2.43949
G1 X87.14 Y73.788 E.01879
G1 X162.86 Y73.788 E2.46606
G1 X163.268 Y74.196 E.01879
G1 X86.732 Y74.196 E2.49264
G1 X86.324 Y74.604 E.01879
G1 X163.676 Y74.604 E2.51921
G1 X164.084 Y75.012 E.01879
M73 P25 R6
G1 X85.916 Y75.012 E2.54579
G1 X85.508 Y75.42 E.01879
G1 X164.492 Y75.42 E2.57236
G1 X164.9 Y75.828 E.01879
G1 X85.1 Y75.828 E2.59894
G1 X84.692 Y76.236 E.01879
M73 P26 R6
G1 X165.308 Y76.236 E2.62552
G1 X165.716 Y76.644 E.01879
G1 X84.284 Y76.644 E2.65209
G1 X83.876 Y77.052 E.01879
G1 X166.124 Y77.052 E2.67867
G1 X166.532 Y77.46 E.01879
M73 P27 R6
G1 X83.468 Y77.46 E2.70524
G1 X83.06 Y77.868 E.01879
G1 X166.94 Y77.868 E2.73182
G1 X167.348 Y78.276 E.01879
G1 X82.652 Y78.276 E2.75839
G1 X82.244 Y78.684 E.01879
G1 X167.756 Y78.684 E2.78497
G1 X168.164 Y79.092 E.01879
M73 P28 R6
G1 X81.836 Y79.092 E2.81154
G1 X81.428 Y79.5 E.01879
M73 P28 R5
G1 X168.572 Y79.5 E2.83812
G1 X168.98 Y79.908 E.01879
G1 X81.02 Y79.908 E2.86469
G1 X80.612 Y80.316 E.01879
M73 P29 R5
G1 X169.388 Y80.316 E2.89127
G1 X169.796 Y80.724 E.01879
G1 X80.204 Y80.724 E2.91785
G1 X79.796 Y81.132 E.01879
G1 X170.204 Y81.132 E2.94442
G1 X170.612 Y81.54 E.01879
M73 P30 R5
G1 X79.388 Y81.54 E2.971
G1 X78.98 Y81.948 E.01879
G1 X171.02 Y81.948 E2.99757
G1 X171.428 Y82.356 E.01879
G1 X78.572 Y82.356 E3.02415
G1 X78.164 Y82.764 E.01879
M73 P31 R5
G1 X171.836 Y82.764 E3.05072
G1 X172.244 Y83.172 E.01879
G1 X77.756 Y83.172 E3.0773
G1 X77.348 Y83.58 E.01879
G1 X172.652 Y83.58 E3.10387
G1 X173.06 Y83.988 E.01879
M73 P32 R5
G1 X76.94 Y83.988 E3.13045
G1 X76.532 Y84.396 E.01879
G1 X173.468 Y84.396 E3.15702
G1 X173.876 Y84.804 E.01879
M73 P33 R5
G1 X76.124 Y84.804 E3.1836
G1 X75.716 Y85.212 E.01879
G1 X174.284 Y85.212 E3.21018
G1 X174.692 Y85.62 E.01879
G1 X75.308 Y85.62 E3.23675
G1 X74.9 Y86.028 E.01879
M73 P34 R5
G1 X175.1 Y86.028 E3.26333
G1 X175.508 Y86.436 E.01879
G1 X74.492 Y86.436 E3.2899
G1 X74.084 Y86.844 E.01879
G1 X175.916 Y86.844 E3.31648
G1 X176.324 Y87.252 E.01879
M73 P35 R5
G1 X73.676 Y87.252 E3.34305
G1 X73.268 Y87.66 E.01879
G1 X176.732 Y87.66 E3.36963
G1 X177.14 Y88.068 E.01879
G1 X72.86 Y88.068 E3.3962
G1 X72.452 Y88.476 E.01879
M73 P36 R5
G1 X177.548 Y88.476 E3.42278
G1 X177.956 Y88.884 E.01879
G1 X72.044 Y88.884 E3.44936
G1 X71.636 Y89.292 E.01879
M73 P37 R5
G1 X178.364 Y89.292 E3.47593
G1 X178.772 Y89.7 E.01879
G1 X71.228 Y89.7 E3.50251
G1 X70.82 Y90.108 E.01879
G1 X179.18 Y90.108 E3.52908
G1 X179.588 Y90.516 E.01879
M73 P38 R5
G1 X70.412 Y90.516 E3.55566
G1 X70.004 Y90.924 E.01879
G1 X179.996 Y90.924 E3.58223
G1 X180.404 Y91.332 E.01879
M73 P39 R5
G1 X69.596 Y91.332 E3.60881
G1 X69.188 Y91.74 E.01879
G1 X180.812 Y91.74 E3.63538
G1 X181.22 Y92.148 E.01879
G1 X68.78 Y92.148 E3.66196
G1 X68.372 Y92.556 E.01879
M73 P40 R4
G1 X181.628 Y92.556 E3.68853
G1 X182.036 Y92.964 E.01879
G1 X67.964 Y92.964 E3.71511
G1 X67.556 Y93.372 E.01879
M73 P41 R4
G1 X182.444 Y93.372 E3.74169
G1 X182.852 Y93.78 E.01879
G1 X67.148 Y93.78 E3.76826
G1 X66.74 Y94.188 E.01879
G1 X183.26 Y94.188 E3.79484
G1 X183.668 Y94.596 E.01879
M73 P42 R4
G1 X66.332 Y94.596 E3.82141
G1 X65.924 Y95.004 E.01879
G1 X184.076 Y95.004 E3.84799
G1 X184.484 Y95.412 E.01879
M73 P43 R4
G1 X65.516 Y95.412 E3.87456
G1 X65.108 Y95.82 E.01879
G1 X184.892 Y95.82 E3.90114
G1 X185.3 Y96.228 E.01879
M73 P44 R4
G1 X64.7 Y96.228 E3.92771
G1 X64.292 Y96.636 E.01879
G1 X185.708 Y96.636 E3.95429
G1 X186.116 Y97.044 E.01879
G1 X63.884 Y97.044 E3.98087
G1 X63.476 Y97.452 E.01879
M73 P45 R4
G1 X186.524 Y97.452 E4.00744
G1 X186.932 Y97.86 E.01879
G1 X63.068 Y97.86 E4.03402
G1 X62.66 Y98.268 E.01879
M73 P46 R4
G1 X187.34 Y98.268 E4.06059
G1 X187.748 Y98.676 E.01879
G1 X62.252 Y98.676 E4.08717
G1 X61.844 Y99.084 E.01879
M73 P47 R4
G1 X188.156 Y99.084 E4.11374
G1 X188.564 Y99.492 E.01879
G1 X61.436 Y99.492 E4.14032
G1 X61.028 Y99.9 E.01879
M73 P48 R4
G1 X188.972 Y99.9 E4.16689
G1 X189.38 Y100.308 E.01879
G1 X60.62 Y100.308 E4.19347
G1 X60.212 Y100.716 E.01879
M73 P49 R4
G1 X189.788 Y100.716 E4.22004
G1 X190.196 Y101.124 E.01879
G1 X59.804 Y101.124 E4.24662
G1 X59.396 Y101.532 E.01879
G1 X190.604 Y101.532 E4.2732
G1 X191.012 Y101.94 E.01879
M73 P50 R4
G1 X58.988 Y101.94 E4.29977
G1 X58.58 Y102.348 E.01879
G1 X191.42 Y102.348 E4.32635
G1 X191.828 Y102.756 E.01879
M73 P51 R4
G1 X58.172 Y102.756 E4.35292
G1 X57.764 Y103.164 E.01879
G1 X192.236 Y103.164 E4.3795
G1 X192.644 Y103.572 E.01879
M73 P52 R3
G1 X57.356 Y103.572 E4.40607
G1 X56.948 Y103.98 E.01879
G1 X193.052 Y103.98 E4.43265
G1 X193.46 Y104.388 E.01879
M73 P53 R3
G1 X56.54 Y104.388 E4.45922
G1 X56.132 Y104.796 E.01879
G1 X193.868 Y104.796 E4.4858
G1 X194.072 Y105 E.00939
M73 P54 R3
G1 X193.868 Y105.204 E.0094
G1 X56.132 Y105.204 E4.48579
G1 X56.54 Y105.612 E.01879
G1 X193.46 Y105.612 E4.45922
G1 X193.052 Y106.02 E.01879
M73 P55 R3
G1 X56.948 Y106.02 E4.43264
G1 X57.356 Y106.428 E.01879
G1 X192.644 Y106.428 E4.40607
G1 X192.236 Y106.836 E.01879
M73 P56 R3
G1 X57.764 Y106.836 E4.37949
G1 X58.172 Y107.244 E.01879
G1 X191.828 Y107.244 E4.35292
G1 X191.42 Y107.652 E.01879
M73 P57 R3
G1 X58.58 Y107.652 E4.32634
G1 X58.988 Y108.06 E.01879
G1 X191.012 Y108.06 E4.29977
G1 X190.604 Y108.468 E.01879
M73 P58 R3
G1 X59.396 Y108.468 E4.27319
G1 X59.804 Y108.876 E.01879
G1 X190.196 Y108.876 E4.24661
G1 X189.788 Y109.284 E.01879
M73 P59 R3
G1 X60.212 Y109.284 E4.22004
G1 X60.62 Y109.692 E.01879
G1 X189.38 Y109.692 E4.19346
G1 X188.972 Y110.1 E.01879
G1 X61.028 Y110.1 E4.16689
G1 X61.436 Y110.508 E.01879
M73 P60 R3
G1 X188.564 Y110.508 E4.14031
G1 X188.156 Y110.916 E.01879
G1 X61.844 Y110.916 E4.11374
G1 X62.252 Y111.324 E.01879
M73 P61 R3
G1 X187.748 Y111.324 E4.08716
G1 X187.34 Y111.732 E.01879
G1 X62.66 Y111.732 E4.06059
G1 X63.068 Y112.14 E.01879
M73 P62 R3
G1 X186.932 Y112.14 E4.03401
G1 X186.524 Y112.548 E.01879
G1 X63.476 Y112.548 E4.00743
G1 X63.884 Y112.956 E.01879
M73 P63 R3
G1 X186.116 Y112.956 E3.98086
G1 X185.708 Y113.364 E.01879
G1 X64.292 Y113.364 E3.95428
G1 X64.7 Y113.772 E.01879
M73 P64 R3
G1 X185.3 Y113.772 E3.92771
G1 X184.892 Y114.18 E.01879
M73 P64 R2
G1 X65.108 Y114.18 E3.90113
G1 X65.516 Y114.588 E.01879
G1 X184.484 Y114.588 E3.87456
G1 X184.076 Y114.996 E.01879
M73 P65 R2
G1 X65.924 Y114.996 E3.84798
G1 X66.332 Y115.404 E.01879
G1 X183.668 Y115.404 E3.82141
G1 X183.26 Y115.812 E.01879
M73 P66 R2
G1 X66.74 Y115.812 E3.79483
G1 X67.148 Y116.22 E.01879
G1 X182.852 Y116.22 E3.76826
G1 X182.444 Y116.628 E.01879
G1 X67.556 Y116.628 E3.74168
G1 X67.964 Y117.036 E.01879
M73 P67 R2
G1 X182.036 Y117.036 E3.7151
G1 X181.628 Y117.444 E.01879
G1 X68.372 Y117.444 E3.68853
G1 X68.78 Y117.852 E.01879
M73 P68 R2
G1 X181.22 Y117.852 E3.66195
G1 X180.812 Y118.26 E.01879
G1 X69.188 Y118.26 E3.63538
G1 X69.596 Y118.668 E.01879
M73 P69 R2
G1 X180.404 Y118.668 E3.6088
G1 X179.996 Y119.076 E.01879
G1 X70.004 Y119.076 E3.58223
G1 X70.412 Y119.484 E.01879
G1 X179.588 Y119.484 E3.55565
G1 X179.18 Y119.892 E.01879
M73 P70 R2
G1 X70.82 Y119.892 E3.52908
G1 X71.228 Y120.3 E.01879
G1 X178.772 Y120.3 E3.5025
G1 X178.364 Y120.708 E.01879
M73 P71 R2
G1 X71.636 Y120.708 E3.47593
G1 X72.044 Y121.116 E.01879
G1 X177.956 Y121.116 E3.44935
G1 X177.548 Y121.524 E.01879
G1 X72.452 Y121.524 E3.42277
G1 X72.86 Y121.932 E.01879
M73 P72 R2
G1 X177.14 Y121.932 E3.3962
G1 X176.732 Y122.34 E.01879
G1 X73.268 Y122.34 E3.36962
G1 X73.676 Y122.748 E.01879
G1 X176.324 Y122.748 E3.34305
G1 X175.916 Y123.156 E.01879
M73 P73 R2
G1 X74.084 Y123.156 E3.31647
G1 X74.492 Y123.564 E.01879
G1 X175.508 Y123.564 E3.2899
G1 X175.1 Y123.972 E.01879
M73 P74 R2
G1 X74.9 Y123.972 E3.26332
G1 X75.308 Y124.38 E.01879
G1 X174.692 Y124.38 E3.23675
G1 X174.284 Y124.788 E.01879
G1 X75.716 Y124.788 E3.21017
G1 X76.124 Y125.196 E.01879
M73 P75 R2
G1 X173.876 Y125.196 E3.18359
G1 X173.468 Y125.604 E.01879
G1 X76.532 Y125.604 E3.15702
G1 X76.94 Y126.012 E.01879
G1 X173.06 Y126.012 E3.13044
G1 X172.652 Y126.42 E.01879
M73 P76 R1
G1 X77.348 Y126.42 E3.10387
G1 X77.756 Y126.828 E.01879
G1 X172.244 Y126.828 E3.07729
G1 X171.836 Y127.236 E.01879
G1 X78.164 Y127.236 E3.05072
G1 X78.572 Y127.644 E.01879
M73 P77 R1
G1 X171.428 Y127.644 E3.02414
G1 X171.02 Y128.052 E.01879
G1 X78.98 Y128.052 E2.99757
G1 X79.388 Y128.46 E.01879
G1 X170.612 Y128.46 E2.97099
G1 X170.204 Y128.868 E.01879
M73 P78 R1
G1 X79.796 Y128.868 E2.94442
G1 X80.204 Y129.276 E.01879
G1 X169.796 Y129.276 E2.91784
G1 X169.388 Y129.684 E.01879
G1 X80.612 Y129.684 E2.89126
G1 X81.02 Y130.092 E.01879
M73 P79 R1
G1 X168.98 Y130.092 E2.86469
G1 X168.572 Y130.5 E.01879
G1 X81.428 Y130.5 E2.83811
G1 X81.836 Y130.908 E.01879
G1 X168.164 Y130.908 E2.81154
G1 X167.756 Y131.316 E.01879
M73 P80 R1
G1 X82.244 Y131.316 E2.78496
G1 X82.652 Y131.724 E.01879
G1 X167.348 Y131.724 E2.75839
G1 X166.94 Y132.132 E.01879
G1 X83.06 Y132.132 E2.73181
G1 X83.468 Y132.54 E.01879
M73 P81 R1
G1 X166.532 Y132.54 E2.70524
G1 X166.124 Y132.948 E.01879
G1 X83.876 Y132.948 E2.67866
G1 X84.284 Y133.356 E.01879
G1 X165.716 Y133.356 E2.65208
G1 X165.308 Y133.764 E.01879
M73 P82 R1
G1 X84.692 Y133.764 E2.62551
G1 X85.1 Y134.172 E.01879
G1 X164.9 Y134.172 E2.59893
G1 X164.492 Y134.58 E.01879
G1 X85.508 Y134.58 E2.57236
G1 X85.916 Y134.988 E.01879
G1 X164.084 Y134.988 E2.54578
G1 X163.676 Y135.396 E.01879
M73 P83 R1
G1 X86.324 Y135.396 E2.51921
G1 X86.732 Y135.804 E.01879
G1 X163.268 Y135.804 E2.49263
G1 X162.86 Y136.212 E.01879
G1 X87.14 Y136.212 E2.46606
G1 X87.548 Y136.62 E.01879
M73 P84 R1
G1 X162.452 Y136.62 E2.43948
G1 X162.044 Y137.028 E.01879
G1 X87.956 Y137.028 E2.41291
G1 X88.364 Y137.436 E.01879
G1 X161.636 Y137.436 E2.38633
G1 X161.228 Y137.844 E.01879
G1 X88.772 Y137.844 E2.35975
G1 X89.18 Y138.252 E.01879
M73 P85 R1
G1 X160.82 Y138.252 E2.33318
G1 X160.412 Y138.66 E.01879
G1 X89.588 Y138.66 E2.3066
G1 X89.996 Y139.068 E.01879
G1 X160.004 Y139.068 E2.28003
G1 X159.596 Y139.476 E.01879
M73 P86 R1
G1 X90.404 Y139.476 E2.25345
G1 X90.812 Y139.884 E.01879
G1 X159.188 Y139.884 E2.22688
G1 X158.78 Y140.292 E.01879
G1 X91.22 Y140.292 E2.2003
G1 X91.628 Y140.7 E.01879
G1 X158.372 Y140.7 E2.17373
G1 X157.964 Y141.108 E.01879
M73 P87 R1
G1 X92.036 Y141.108 E2.14715
G1 X92.444 Y141.516 E.01879
G1 X157.556 Y141.516 E2.12057
G1 X157.148 Y141.924 E.01879
G1 X92.852 Y141.924 E2.094
G1 X93.26 Y142.332 E.01879
G1 X156.74 Y142.332 E2.06742
G1 X156.332 Y142.74 E.01879
M73 P88 R1
G1 X93.668 Y142.74 E2.04085
G1 X94.076 Y143.148 E.01879
M73 P88 R0
G1 X155.924 Y143.148 E2.01427
G1 X155.516 Y143.556 E.01879
G1 X94.484 Y143.556 E1.9877
G1 X94.892 Y143.964 E.01879
G1 X155.108 Y143.964 E1.96112
G1 X154.7 Y144.372 E.01879
M73 P89 R0
G1 X95.3 Y144.372 E1.93455
G1 X95.708 Y144.78 E.01879
G1 X154.292 Y144.78 E1.90797
G1 X153.884 Y145.188 E.01879
G1 X96.116 Y145.188 E1.8814
G1 X96.524 Y145.596 E.01879
G1 X153.476 Y145.596 E1.85482
G1 X153.068 Y146.004 E.01879
G1 X96.932 Y146.004 E1.82824
G1 X97.34 Y146.412 E.01879
M73 P90 R0
G1 X152.66 Y146.412 E1.80167
G1 X152.252 Y146.82 E.01879
G1 X97.748 Y146.82 E1.77509
G1 X98.156 Y147.228 E.01879
G1 X151.844 Y147.228 E1.74852
G1 X151.436 Y147.636 E.01879
G1 X98.564 Y147.636 E1.72194
G1 X98.972 Y148.044 E.01879
M73 P91 R0
G1 X151.028 Y148.044 E1.69537
G1 X150.62 Y148.452 E.01879
G1 X99.38 Y148.452 E1.66879
G1 X99.788 Y148.86 E.01879
G1 X150.212 Y148.86 E1.64222
G1 X149.804 Y149.268 E.01879
G1 X100.196 Y149.268 E1.61564
G1 X100.604 Y149.676 E.01879
G1 X149.396 Y149.676 E1.58907
G1 X148.988 Y150.084 E.01879
M73 P92 R0
G1 X101.012 Y150.084 E1.56249
G1 X101.42 Y150.492 E.01879
G1 X148.58 Y150.492 E1.53591
G1 X148.172 Y150.9 E.01879
G1 X101.828 Y150.9 E1.50934
G1 X102.236 Y151.308 E.01879
G1 X147.764 Y151.308 E1.48276
G1 X147.356 Y151.716 E.01879
G1 X102.644 Y151.716 E1.45619
G1 X103.052 Y152.124 E.01879
G1 X146.948 Y152.124 E1.42961
G1 X146.54 Y152.532 E.01879
M73 P93 R0
G1 X103.46 Y152.532 E1.40304
G1 X103.868 Y152.94 E.01879
G1 X146.132 Y152.94 E1.37646
G1 X145.724 Y153.348 E.01879
G1 X104.276 Y153.348 E1.34989
G1 X104.684 Y153.756 E.01879
G1 X145.316 Y153.756 E1.32331
G1 X144.908 Y154.164 E.01879
G1 X105.092 Y154.164 E1.29673
G1 X105.5 Y154.572 E.01879
G1 X144.5 Y154.572 E1.27016
G1 X144.092 Y154.98 E.01879
M73 P94 R0
G1 X105.908 Y154.98 E1.24358
G1 X106.316 Y155.388 E.01879
G1 X143.684 Y155.388 E1.21701
G1 X143.276 Y155.796 E.01879
G1 X106.724 Y155.796 E1.19043
G1 X107.132 Y156.204 E.01879
G1 X142.868 Y156.204 E1.16386
G1 X142.46 Y156.612 E.01879
G1 X107.54 Y156.612 E1.13728
G1 X107.948 Y157.02 E.01879
G1 X142.052 Y157.02 E1.11071
G1 X141.644 Y157.428 E.01879
M73 P95 R0
G1 X108.356 Y157.428 E1.08413
G1 X108.764 Y157.836 E.01879
G1 X141.236 Y157.836 E1.05756
G1 X140.828 Y158.244 E.01879
G1 X109.172 Y158.244 E1.03098
G1 X109.58 Y158.652 E.01879
G1 X140.42 Y158.652 E1.0044
G1 X140.012 Y159.06 E.01879
G1 X109.988 Y159.06 E.97783
G1 X110.396 Y159.468 E.01879
G1 X139.604 Y159.468 E.95125
G1 X139.196 Y159.876 E.01879
G1 X110.804 Y159.876 E.92468
G1 X111.212 Y160.284 E.01879
M73 P96 R0
G1 X138.788 Y160.284 E.8981
G1 X138.38 Y160.692 E.01879
G1 X111.62 Y160.692 E.87153
G1 X112.028 Y161.1 E.01879
G1 X137.972 Y161.1 E.84495
G1 X137.564 Y161.508 E.01879
G1 X112.436 Y161.508 E.81838
G1 X112.844 Y161.916 E.01879
G1 X137.156 Y161.916 E.7918
G1 X136.748 Y162.324 E.01879
G1 X113.252 Y162.324 E.76522
G1 X113.66 Y162.732 E.01879
G1 X136.34 Y162.732 E.73865
G1 X135.932 Y163.14 E.01879
G1 X114.068 Y163.14 E.71207
G1 X114.476 Y163.548 E.01879
G1 X135.524 Y163.548 E.6855
G1 X135.116 Y163.956 E.01879
M73 P97 R0
G1 X114.884 Y163.956 E.65892
G1 X115.292 Y164.364 E.01879
G1 X134.708 Y164.364 E.63235
G1 X134.3 Y164.772 E.01879
G1 X115.7 Y164.772 E.60577
G1 X116.108 Y165.18 E.01879
G1 X133.892 Y165.18 E.5792
G1 X133.484 Y165.588 E.01879
G1 X116.516 Y165.588 E.55262
G1 X116.924 Y165.996 E.01879
G1 X133.076 Y165.996 E.52605
G1 X132.668 Y166.404 E.01879
G1 X117.332 Y166.404 E.49947
G1 X117.74 Y166.812 E.01879
G1 X132.26 Y166.812 E.47289
G1 X131.852 Y167.22 E.01879
G1 X118.148 Y167.22 E.44632
G1 X118.556 Y167.628 E.01879
G1 X131.444 Y167.628 E.41974
G1 X131.036 Y168.036 E.01879
G1 X118.964 Y168.036 E.39317
G1 X119.372 Y168.444 E.01879
M73 P98 R0
G1 X130.628 Y168.444 E.36659
G1 X130.22 Y168.852 E.01879
G1 X119.78 Y168.852 E.34002
G1 X120.188 Y169.26 E.01879
G1 X129.812 Y169.26 E.31344
G1 X129.404 Y169.668 E.01879
G1 X120.596 Y169.668 E.28687
G1 X121.004 Y170.076 E.01879
G1 X128.996 Y170.076 E.26029
G1 X128.588 Y170.484 E.01879
G1 X121.412 Y170.484 E.23372
G1 X121.82 Y170.892 E.01879
G1 X128.18 Y170.892 E.20714
G1 X127.772 Y171.3 E.01879
G1 X122.228 Y171.3 E.18056
G1 X122.636 Y171.708 E.01879
G1 X127.364 Y171.708 E.15399
G1 X126.956 Y172.116 E.01879
G1 X123.044 Y172.116 E.12741
G1 X123.452 Y172.524 E.01879
G1 X126.548 Y172.524 E.10084
G1 X126.14 Y172.932 E.01879
G1 X123.86 Y172.932 E.07426
G1 X124.268 Y173.34 E.01879
G1 X125.732 Y173.34 E.04769
G1 X125.324 Y173.748 E.01879
G1 X124.417 Y173.748 E.02955
; stop printing object Cube id:15 copy 0
G1 E-.3 F1800
;WIPE_START
G1 F3600
G1 X125.324 Y173.748 E-.45364
G1 X125.39 Y173.682 E-.04636
;WIPE_END
M106 S0
;TYPE:Custom
; filament end gcode
G1 Z1.2 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z49.2 F720 ; Move print head further up
M73 P99 R0
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; EXECUTABLE_BLOCK_END
; filament used [mm] = 823.68
; filament used [cm3] = 1.98
; filament used [g] = 2.60
; filament cost = 0.07
; total filament used [g] = 2.60
; total filament cost = 0.07
; total layers count = 1
; estimated printing time (normal mode) = 8m 21s
; estimated first layer printing time (normal mode) = 7s
; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 70
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = C:\\Users\\jensm\\Desktop\\mk2_bed.stl
; bed_custom_texture = C:\\Users\\jensm\\Desktop\\mk2.svg
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 25
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0
; brim_type = no_brim
; brim_width = 0
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = partiallybridge
; curr_bed_type = High Temp Plate
; default_acceleration = 500
; default_bed_type = 
; default_filament_colour = ""
; default_filament_profile = "Prusament PLA"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.15mm OPTIMAL
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = brim_type;counterbore_hole_bridging;elefant_foot_compensation;enable_support;gap_infill_speed;initial_layer_speed;inner_wall_acceleration;internal_solid_infill_speed;precise_outer_wall;skirt_loops;sparse_infill_pattern;sparse_infill_speed;support_speed;top_surface_speed;travel_acceleration;compatible_printers;filament_flow_ratio;bed_custom_model;bed_custom_texture;before_layer_change_gcode;change_filament_gcode;default_filament_profile;default_print_profile;deretraction_speed;extruder_clearance_height_to_lid;extruder_clearance_height_to_rod;extruder_clearance_radius;extruder_colour;gcode_flavor;layer_change_gcode;machine_end_gcode;machine_max_acceleration_e;machine_max_acceleration_extruding;machine_max_acceleration_retracting;machine_max_acceleration_travel;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_acceleration_z;machine_max_jerk_e;machine_max_jerk_x;machine_max_jerk_y;machine_max_jerk_z;machine_max_speed_e;machine_max_speed_x;machine_max_speed_y;machine_max_speed_z;machine_min_extruding_rate;machine_min_travel_rate;machine_pause_gcode;machine_start_gcode;max_layer_height;min_layer_height;nozzle_type;print_host;printable_area;printable_height;printer_model;printer_notes;printer_variant;printhost_apikey;retract_before_wipe;retract_length_toolchange;retract_lift_below;retraction_minimum_travel;support_multi_bed_types;thumbnails;z_hop_types
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0.2
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_clearance_height_to_lid = 120
; extruder_clearance_height_to_rod = 40
; extruder_clearance_radius = 40
; extruder_colour = #FF8000
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.31
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_flow_ratio = 0.96
; filament_ids = OGFL01
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 22
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PolyTerra PLA @System - Copy"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; Filament gcode\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Polymaker
; filename_format = {input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 40
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 55
; hot_plate_temp_initial_layer = 55
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 15%
; inherits_group = Untitled;"PolyTerra PLA @System";"MyKlipper 0.4 nozzle"
; initial_layer_acceleration = 300
; initial_layer_infill_speed = 60
; initial_layer_jerk = 9
; initial_layer_line_width = 0
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 20
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 300
; inner_wall_jerk = 9
; inner_wall_line_width = 0
; inner_wall_speed = 60
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 70
; ironing_angle = -1
; ironing_fan_speed = -1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.1
; ironing_speed = 20
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0
; long_retractions_when_cut = 0
; machine_end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM900 K0 ; reset LA\nM84 ; disable motors
; machine_load_filament_time = 0
; machine_max_acceleration_e = 800
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000
; machine_max_acceleration_y = 1000
; machine_max_acceleration_z = 200
; machine_max_jerk_e = 5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.4
; machine_max_junction_deviation = 0,0
; machine_max_speed_e = 120
; machine_max_speed_x = 200
; machine_max_speed_y = 200
; machine_max_speed_z = 12
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = M601
; machine_start_gcode = M862.3 P \"[printer_model]\" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.2.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM204 S[machine_max_acceleration_extruding] T[machine_max_acceleration_retracting] ; MK2 firmware only supports the old M204 format\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Z2.0 F3000 ;Move Z Axis up\nG1 X{first_layer_print_min[0]-10} Y{first_layer_print_min[1]} Z0.8 F5000 ; Move to start\nM109 S[nozzle_temperature_initial_layer] ; wait for nozzle temp to stabilize\nG92 E0 ;Reset Extruder\nG1 X{first_layer_print_min[0]-10} Y{first_layer_print_min[1]+30} E30 F360.0 ; Extrude 30mm in Y\nG92 E0 ;Reset Extruder\nG1 E-0.5 F2100 ; Retract\nG1 Y{first_layer_print_min[1]+40} F5000 ; Move 10mm in Y\nG92 E0  ;Reset Extrude
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.25
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.07
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 500
; outer_wall_jerk = 9
; outer_wall_line_width = 0
; outer_wall_speed = 60
; overhang_1_4_speed = 0
; overhang_2_4_speed = 0
; overhang_3_4_speed = 0
; overhang_4_4_speed = 0
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = Standard
; printable_area = 0x0,250x0,250x210,0x210
; printable_height = 210
; printer_model = 
; printer_notes = Don't remove the following keywords! These keywords are used in the \"compatible printer\" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK2\n
; printer_settings_id = Pretty PLA (Testi uus prime)
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 0
; required_nozzle_HRC = 3
; resolution = 0.01
; resonance_avoidance = 0
; retract_before_wipe = 10%
; retract_length_toolchange = 4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 2
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 1
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 4
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 0,90
; sparse_infill_acceleration = 100%
; sparse_infill_density = 20%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0
; sparse_infill_pattern = cubic
; sparse_infill_rotate_template = 
; sparse_infill_speed = 70
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 45
; supertack_plate_temp_initial_layer = 45
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 0
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 3
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 1
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 50
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = tree(manual)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 55
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG, 300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 4
; top_shell_thickness = 0.6
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 500
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 0
; top_surface_pattern = monotonicline
; top_surface_speed = 40
; travel_acceleration = 180
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 120
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 40
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_wall_type = rectangle
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Slope Lift
; z_offset = 0
; first_layer_bed_temperature = 55
; bed_shape = 0x0,250x0,250x210,0x210
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END
