M118 E1 OCTOAPP_DISABLE_LAYER_MAXIC
; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.0 on 2025-09-13 at 10:37:23
; total layer number: 3
;_GP_TOTAL_LAYER_NUMBER_PLACEHOLDER
; filament_density: 1.31
; filament_diameter: 1.75
; max_z_height: 0.60
; HEADER_BLOCK_END
; THUMBNAIL_BLOCK_START
;
; thumbnail begin 48x48 764
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAACBElEQVR4Ae2YTUsCURSG301EQZibFk
; URRa2UjIQIC6SoKDcGUbqI7AtDCO2bVhLUIiJc9AOEVkGEtW0zbmrRoiDaBIUQ1KaFP2HiLCbGwXS8
; 8+EV7gMHRIbhnXvuczkzgEAgEAh4xdUCz1QPgqhFol4kfvYgv8eRp9+OejSjFqCgNyFIFF5d9F+7A5
; 3gmZALEW1wdSndAI+cTyNdKry2G9xsKRL1KYqc3vDqblRd8F0fkpUG19bRKFK2d4NWXYrg2Wh4pehe
; dE/YgXI8ml2WC05trkRU1rLkuGUV1Ug3TBOcJLMruKmCmy0qazEJbpWoRraUrnmKLriYQYan8OoqKT
; hJQ0/Ka3h1N2jmKgh/Mm798Wh2nU0i/fcAi31IPa7xv/pKvW1ADruRKuhChwOe63nkvnf4Dn81h3yX
; E/5/Rd4aQvojzl9wWvWDEUjQg7sF/mwEeV66kV2CXHLVi0Fbat+H9Odm9YJ/bUM+HoPkbDAwGwV6kL
; hfsV/wlxjkQC+SMAPqxuWsfYKXFZWVdS9SrzHrgpOoy/2q890Kup3wWCH43QKDqKw01qHZLMFJVDoe
; DYnKymAbgtQN1vAPq5CHO6r8nYgEP/QjU+mWOp2A1Npk04u8Hmie0iN40TmGF8rNU7dhi45Hs9HOUx
; XNMbygCE5zzECr5gWkVqAtxZWoAoFAINDyC4lOFVdiKzjEAAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END
; THUMBNAIL_BLOCK_START
;
; thumbnail begin 300x300 3444
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAJ3klEQVR4Ae3dzYteVx3A8bMJYkCSwi
; BYaCgt0kArLVWw0CwmYotaLIlorUVDipFIUBPxBXeV4kYQshDduIgRBN0YQUGQQnRhF1IcKC4UlICg
; Gxf5E0ZP2yHP3DnPzPPc576cl88HvlC6m2l7ufeX8zsNAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYBYn3hVOBoCcPfbe8MTti2EnFv86AOTo8ofCtf9+
; O+zu9Y+r4W78e962gGzEB9LPzodbiw+rxX79Yrj9wInwYACY09MPhO34JrXsYbX4tvXiY+FiAJjD9z
; 4Srh/1oOr2w0+EGz4RgcnEYfpfLoc76z6s9ooD+Y+/P5wLAGPqDtb7ZiAPjCY+WOLwfIiHlYE8MJo4
; LB/6QZV62woAm4hD8jEfVt23LZ+IwNo2Haxv8rZlIA+s7FtPh1emflB1i0cmvG0BS+3tAc79sNrLPi
; KQNNRxhTE+EQ3kgbcctQeYS44/QONW3QPM6W3LQB4a1GcPMJcM5KERuQ3W+2YgD5XLdbDeN/uIUKGx
; 9gBzyUAeKjH2HmBOb1suCISCTbkHmEsuCITCzLUHmEsuCIRC5LAHmEMG8pCxWo4rDF0cyDv+ABmp7b
; jC0NlHhAzEz50WB+t9c/wBZtL6YL1v9hFhYiXvAeaSfUQYmcH6sNlHhJEYrI+T4w8woFIu2Cs9A3nY
; UGkX7JWefUToyWB9vuwjwoocV8gj+4hwBIP1vDKQh4TaL9grPQN5eEcrF+yVnn1EmmcPsLzi25ZPRJ
; pisF529hFphgv26sk+ItWyB1hn9hGpjuMKdWcgTxXsAbaV4w8Uyx5gm9lHpDj2AGUfkew5rqDF4kA+
; vmkHyI3BulLZRyQr9gC1SgbyzM4eoNbJ8QdmYw9QfbOPyGQM1jVE8d8h+4iMyh6ghix+ItpHZHD2AD
; Vm8RPRPiKDcFxBU2Qgz0bia7rBuqbO8QfWZrCuOXNBICuzB6hcMpBnKYN15ZgLAjnAYF05Zx+Rt7hg
; TyVlIN8wF+ypxFwQ2CCDdZWeCwIb4LiCaioO5B1/qJQ9QNWYgXxl4pDScQXVnoF8BVywp5ayj1gwe4
; BqNRcEFsRgXbKPWATHFaT92UfMkD1AaXn2ETNiD1A6OscfZmYPUFo/xx9mYA9Q6p99xAkZrEvDZB9x
; RI4rSMNnH3EEBuvSeBnIDyT+AuOQsKR/+FKpGchvwB6gNH32EXuwByjNm33EFRisS/lkH/EQLtiT8s
; w+4gJ7gFL+2UcMjitIJdXsQN4eoFRuTR1/iK+V9gClsmtiIG8PUKqrKgfyButSvVU1kDdYl+qv+H1E
; g3WpvYocyNsDlNqtqAsC7QFKimV9QaA9QEndsrwg0B6gpGVlM5B3XEHSqsWB/GzHHxxXkLRuk+8jxt
; c6g3VJmzTJBYEG65KGatR9RHuAksZo0H1Eg3VJYzfIPqLBuqSp2uj4wzMPh4v/+npZP7Cksvv3N8Lu
; 84/0+FPEZx8O137+qbD75y+V9QNLKrPXL4Xd7z8Tdj/6UHglrCs+sH56LuzGfvO5sPufb5b1w0sqp1
; 999u2H1SAPrFh82/rrlbJ+CZLy7u9fDbs/eu7ew6r3Ays6vRW2f/xcuLv44Prjy962JG3e77+w/0EV
; e+i+sB02cepEeOLSk+HG4kMrvr7982pZvxxJeRTfqn7y/P4H1f//dPD2fe8e8OK/+Im4+LZlIC9p3f
; 7w8sG3qjOnRtotjG9bP3g23Fl824oDeccfJB1WPK6wOFiPfedMuHP/eya4veGlD4TrBvKSVil+Al7/
; 2P6H1QuPhhthSvFty0Be0mH99qURBuubMJCX1G3ZYD3k4Mn3hXOpgby3Lam9UoP1D96f2f9FJ34ifu
; 3D4ZaBvNRmcbD+i08ffKuaZLDeVxzId9+2dr5c1i9e0nq9cfngYP2Tj4TroQSp4w+vXfCJKNVY97jC
; d8+Gu7MO1vtKDeQdf5DqKLUHmM1gvS8Deam+UnuA2Q3W+0rtI8aBvOMPUllNsgeYC/uIUrmljiv0vg
; qmFMv2EX0iSnmW2gMsdrDel31EKf9Sg/XJ9wBzYR9Ryrfs9gBzcPxYOGkfUcqnpgbrfTn+IM3fpBfs
; lc4+ojRPRe4B5iI1kLePKI3Tm1cK3gPMhX1Eafy6g/XmjisMzT6iNHxV7gHmwkBeGq4iLtgrnYG8tF
; lxsH7zvMH6pOwjSuv3+qUG9wBzYR9RWr3m9wBz0R3I20eU7pUarF94PNwKzOf0Vti2jyjtL3XBnreq
; TKQuCLSPqBazB1gQA3m1nD3AAsW3rVfPhh3HH9RKqT3Aq0+FHccVCuKCQLWQPcCKuCBQNWcPsFIG8q
; qpZYP1QD3sI6qG7AE2xD6iSs0eYMPiQL77tuWCQOVaag/QYL0xqX3E333eJ6Lyyh4g+3QH8r/8jOMP
; mj8X7LFUdx8xfiL+6YvetjRP9gA5UmofMQ7kHX/QVNkDZG32ETVHqeMKLthjJcsuCHT8QUMXjysYrD
; MI+4gas9Rg/YVHw40AfdlH1Bh19wAN1hnM8WPhpH1EDZHBOpOxj6hNcsEek7OPqHVLXbBnD5BJpQby
; 9hHVzQV7ZCN1/OG1Cz4R9XYu2CNLqYG84w/tZg+Q7BnIK+aCPYphIN9ucbCeOq5gsE727CO2VeqCPX
; uAFGXZPqJPxLqyB0hVugN5+4h1ZA+QatlHrCsX7FG9rePhQfuIZWcPkOacORUuGsiXlz1AmhU/EV89
; G3Ycf8i/1B7g1afCjuMKNMc+Yt7ZA4QO+4h5Zg8QDpEayP/tK2X9R15D9gBhRfYR580eIKzJPuL0xc
; H6zfP2AKG3OJB3/GH8UnuABuvQg33EcbMHCCOwjzhsBuswstNbYbv7iWgfcf3sAcJE4ieifcR+2QOE
; mbggcL1SxxVcsAcTWjaQd/zhXvG4Qmqw7rgCzCS1j2gg74I9yJYLAvfX3QM0WIcMtT6QXzZYD0CeWt
; 1HdMEeFKqlfcTUBXv2AKFAtV8Q+MZlF+xBVWq9INAFe1Cx1EC+xOMP9gChEaUP5FN7gC7Yg4ql9hFz
; H8jfuWYPEJpWyj5i6oI9e4DQoNwvCHTBHnBAbvuI9gCBQ+Wyj2gPEFjJ8WPh5Fz7iC7YA3qZ+viDPU
; BgI1PsI9oDBAY11j7im1fsAQIjGHof0R4gMLpN9xHtAQKT6juQTw3W7QECo1tnIB8H6zfPG6wDM4sD
; +cP2EVN7gAbrwGyW7SPaAwSy1R3ILz6sLjwebgWAnJzeCtt7n4j2AIHs7V0QaA8QAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4FD/A5ogOG0O/2nhAAAA
; AElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; EXECUTABLE_BLOCK_START
M73 P0 R2
M201 X1000 Y1000 Z200 E800
M203 X200 Y200 Z12 E120
M204 P1250 R1000 T1250
M205 X10.00 Y10.00 Z0.40 E5.00 ; sets the jerk limits, mm/sec
;TYPE:Custom
M862.3 P "" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.2.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M204 S1250 T1000 ; MK2 firmware only supports the old M204 format
M104 S220 ; set extruder temp
M140 S55 ; set bed temp
M190 S55 ; wait for bed temp
M109 S220 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Z2.0 F3000 ;Move Z Axis up
G1 X100.5 Y90.5 Z0.8 F5000 ; Move to start
M109 S220 ; wait for nozzle temp to stabilize
G92 E0 ;Reset Extruder
G1 X100.5 Y120.5 E30 F360.0 ; Extrude 30mm in Y
M73 P1 R2
G92 E0 ;Reset Extruder
G1 E-0.5 F2100 ; Retract
M73 P4 R2
G1 Y130.5 F5000 ; Move 10mm in Y
G92 E0  ;Reset Extrude
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
M106 S0
;LAYER_CHANGE
M117 DASHBOARD_LAYER_INDICATOR 1
M118 E1 OCTOAPP_LAYER LAYER=0
M117 DASHBOARD_LAYER_INDICATOR 1
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2
G1 E-.8 F1800
;_SET_FAN_SPEED_CHANGING_LAYER
M204 S300
; printing object Cube id:13844432977387129179 copy 0
G1 X136.646 Y116.646 F7200
G1 Z.6
M73 P5 R2
G1 Z.2
G1 E.8 F1800
;TYPE:Inner wall
;WIDTH:0.449999
G1 F1200
G1 X113.354 Y116.646 E.7569
G1 X113.354 Y93.354 E.7569
M73 P6 R2
G1 X136.646 Y93.354 E.7569
M73 P7 R2
G1 X136.646 Y116.606 E.7556
G1 X137.075 Y117.075 F7200
M73 P8 R2
;TYPE:Outer wall
G1 F1200
G1 X112.925 Y117.075 E.78475
G1 X112.925 Y92.925 E.78475
M73 P9 R2
G1 X137.075 Y92.925 E.78475
M73 P10 R2
G1 X137.075 Y117.035 E.78345
M73 P11 R2
G1 E-.08 F1800
M73 P12 R2
;WIPE_START
G1 F1200
G1 X136.075 Y117.037 E-.72
;WIPE_END
G1 X136.226 Y109.406 Z.6 F7200
G1 X136.524 Y94.301 Z.6
G1 Z.2
G1 E.8 F1800
;TYPE:Bottom surface
;WIDTH:0.451086
G1 F3600
G1 X135.882 Y93.659 E.02958
G1 X135.305 Y93.659 E.01881
G1 X136.341 Y94.695 E.04774
G1 X136.341 Y95.272 E.01881
G1 X134.728 Y93.659 E.07434
G1 X134.151 Y93.659 E.01881
M73 P13 R2
G1 X136.341 Y95.849 E.10093
G1 X136.341 Y96.427 E.01881
G1 X133.573 Y93.659 E.12753
G1 X132.996 Y93.659 E.01881
G1 X136.341 Y97.004 E.15413
G1 X136.341 Y97.581 E.01881
G1 X132.419 Y93.659 E.18073
G1 X131.842 Y93.659 E.01881
G1 X136.341 Y98.158 E.20732
G1 X136.341 Y98.736 E.01881
G1 X131.264 Y93.659 E.23392
G1 X130.687 Y93.659 E.01881
G1 X136.341 Y99.313 E.26052
G1 X136.341 Y99.89 E.01881
M73 P14 R2
G1 X130.11 Y93.659 E.28712
G1 X129.533 Y93.659 E.01881
G1 X136.341 Y100.467 E.31371
G1 X136.341 Y101.044 E.01881
G1 X128.956 Y93.659 E.34031
G1 X128.378 Y93.659 E.01881
G1 X136.341 Y101.622 E.36691
G1 X136.341 Y102.199 E.01881
M73 P15 R2
G1 X127.801 Y93.659 E.39351
G1 X127.224 Y93.659 E.01881
G1 X136.341 Y102.776 E.4201
G1 X136.341 Y103.353 E.01881
G1 X126.647 Y93.659 E.4467
G1 X126.069 Y93.659 E.01881
G1 X136.341 Y103.931 E.4733
G1 X136.341 Y104.508 E.01881
M73 P16 R2
G1 X125.492 Y93.659 E.4999
G1 X124.915 Y93.659 E.01881
G1 X136.341 Y105.085 E.52649
G1 X136.341 Y105.662 E.01881
G1 X124.338 Y93.659 E.55309
G1 X123.76 Y93.659 E.01881
M73 P17 R2
G1 X136.341 Y106.24 E.57969
G1 X136.341 Y106.817 E.01881
G1 X123.183 Y93.659 E.60628
G1 X122.606 Y93.659 E.01881
G1 X136.341 Y107.394 E.63288
G1 X136.341 Y107.971 E.01881
M73 P18 R1
G1 X122.029 Y93.659 E.65948
G1 X121.451 Y93.659 E.01881
G1 X136.341 Y108.549 E.68608
G1 X136.341 Y109.126 E.01881
G1 X120.874 Y93.659 E.71267
G1 X120.297 Y93.659 E.01881
M73 P19 R1
G1 X136.341 Y109.703 E.73927
G1 X136.341 Y110.28 E.01881
G1 X119.72 Y93.659 E.76587
G1 X119.143 Y93.659 E.01881
G1 X136.341 Y110.857 E.79247
G1 X136.341 Y111.435 E.01881
M73 P20 R1
G1 X118.565 Y93.659 E.81906
G1 X117.988 Y93.659 E.01881
G1 X136.341 Y112.012 E.84566
G1 X136.341 Y112.589 E.01881
M73 P21 R1
G1 X117.411 Y93.659 E.87226
G1 X116.834 Y93.659 E.01881
G1 X136.341 Y113.166 E.89886
G1 X136.341 Y113.744 E.01881
G1 X116.256 Y93.659 E.92545
G1 X115.679 Y93.659 E.01881
M73 P22 R1
G1 X136.341 Y114.321 E.95205
G1 X136.341 Y114.898 E.01881
G1 X115.102 Y93.659 E.97865
G1 X114.525 Y93.659 E.01881
M73 P23 R1
G1 X136.341 Y115.475 E1.00525
G1 X136.341 Y116.053 E.01881
G1 X113.947 Y93.659 E1.03184
G1 X113.659 Y93.659 E.0094
M73 P24 R1
G1 X113.659 Y93.948 E.0094
G1 X136.052 Y116.341 E1.03184
G1 X135.475 Y116.341 E.01881
G1 X113.659 Y94.525 E1.00524
G1 X113.659 Y95.102 E.01881
M73 P25 R1
G1 X134.898 Y116.341 E.97864
G1 X134.321 Y116.341 E.01881
G1 X113.659 Y95.679 E.95205
G1 X113.659 Y96.256 E.01881
M73 P26 R1
G1 X133.744 Y116.341 E.92545
G1 X133.166 Y116.341 E.01881
G1 X113.659 Y96.834 E.89885
G1 X113.659 Y97.411 E.01881
G1 X132.589 Y116.341 E.87225
G1 X132.012 Y116.341 E.01881
M73 P27 R1
G1 X113.659 Y97.988 E.84566
G1 X113.659 Y98.565 E.01881
G1 X131.435 Y116.341 E.81906
G1 X130.857 Y116.341 E.01881
M73 P28 R1
G1 X113.659 Y99.143 E.79246
G1 X113.659 Y99.72 E.01881
G1 X130.28 Y116.341 E.76587
G1 X129.703 Y116.341 E.01881
G1 X113.659 Y100.297 E.73927
G1 X113.659 Y100.874 E.01881
M73 P29 R1
G1 X129.126 Y116.341 E.71267
G1 X128.548 Y116.341 E.01881
G1 X113.659 Y101.452 E.68607
G1 X113.659 Y102.029 E.01881
M73 P30 R1
G1 X127.971 Y116.341 E.65948
G1 X127.394 Y116.341 E.01881
G1 X113.659 Y102.606 E.63288
G1 X113.659 Y103.183 E.01881
G1 X126.817 Y116.341 E.60628
G1 X126.24 Y116.341 E.01881
M73 P31 R1
G1 X113.659 Y103.76 E.57968
G1 X113.659 Y104.338 E.01881
G1 X125.662 Y116.341 E.55309
G1 X125.085 Y116.341 E.01881
G1 X113.659 Y104.915 E.52649
G1 X113.659 Y105.492 E.01881
G1 X124.508 Y116.341 E.49989
M73 P32 R1
G1 X123.931 Y116.341 E.01881
G1 X113.659 Y106.069 E.47329
G1 X113.659 Y106.647 E.01881
G1 X123.353 Y116.341 E.4467
G1 X122.776 Y116.341 E.01881
G1 X113.659 Y107.224 E.4201
G1 X113.659 Y107.801 E.01881
M73 P33 R1
G1 X122.199 Y116.341 E.3935
G1 X121.622 Y116.341 E.01881
G1 X113.659 Y108.378 E.3669
G1 X113.659 Y108.956 E.01881
G1 X121.044 Y116.341 E.34031
G1 X120.467 Y116.341 E.01881
G1 X113.659 Y109.533 E.31371
G1 X113.659 Y110.11 E.01881
M73 P34 R1
G1 X119.89 Y116.341 E.28711
G1 X119.313 Y116.341 E.01881
G1 X113.659 Y110.687 E.26051
G1 X113.659 Y111.265 E.01881
G1 X118.735 Y116.341 E.23392
G1 X118.158 Y116.341 E.01881
G1 X113.659 Y111.842 E.20732
G1 X113.659 Y112.419 E.01881
G1 X117.581 Y116.341 E.18072
G1 X117.004 Y116.341 E.01881
G1 X113.659 Y112.996 E.15413
M73 P35 R1
G1 X113.659 Y113.573 E.01881
G1 X116.427 Y116.341 E.12753
G1 X115.849 Y116.341 E.01881
G1 X113.659 Y114.151 E.10093
G1 X113.659 Y114.728 E.01881
G1 X115.272 Y116.341 E.07433
G1 X114.695 Y116.341 E.01881
G1 X113.659 Y115.305 E.04774
G1 X113.659 Y115.882 E.01881
G1 X114.301 Y116.524 E.02958
; stop printing object Cube id:13844432977387129179 copy 0
M106 S255
;LAYER_CHANGE
M117 DASHBOARD_LAYER_INDICATOR 2
M118 E1 OCTOAPP_LAYER LAYER=1
M117 DASHBOARD_LAYER_INDICATOR 2
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4
G1 E-.3 F1800
;WIPE_START
G1 F3600
G1 X113.659 Y115.882 E-.45392
G1 X113.659 Y115.79 E-.04608
;WIPE_END
;_SET_FAN_SPEED_CHANGING_LAYER
M204 S500
;CUSTOM_GCODE
M600
; printing object Cube id:13844432977387129179 copy 0
M204 S180
G1 X121.283 Y116.138 Z.8 F7200
G1 X136.846 Y116.846 Z.8
G1 Z.4
M73 P36 R1
G1 E.8 F1800
M204 S300
;TYPE:Inner wall
;WIDTH:0.449999
G1 F3600
G1 X113.154 Y116.846 E.7699
G1 X113.154 Y93.154 E.7699
G1 X136.846 Y93.154 E.7699
M73 P37 R1
G1 X136.846 Y116.806 E.7686
M204 S180
G1 X137.275 Y117.275 F7200
M204 S500
;TYPE:Outer wall
G1 F3600
G1 X112.725 Y117.275 E.79775
G1 X112.725 Y92.725 E.79775
M73 P38 R1
G1 X137.275 Y92.725 E.79775
G1 X137.275 Y117.235 E.79645
M204 S180
G1 E-.3 F1800
M73 P39 R1
;WIPE_START
G1 F3600
G1 X136.275 Y117.237 E-.5
;WIPE_END
G1 X135.057 Y116.439 Z.8 F7200
G1 Z.4
G1 E.8 F1800
M204 S500
;TYPE:Internal solid infill
G1 F4200
G1 X136.439 Y116.439 E.04492
G1 X136.439 Y115.057 E.04492
G1 X135.085 Y116.411 E.06223
M204 S180
G1 X136.06 Y115.991 F7200
M204 S500
;WIDTH:0.445632
G1 F4200
G1 X136.009 Y115.991 E.00162
G1 X135.984 Y116.034 E.00162
G1 X136.009 Y116.078 E.00162
G1 X136.065 Y116.069 E.00181
M204 S180
G1 X136.684 Y114.294 F7200
M204 S500
;WIDTH:0.45107
G1 F4200
G1 X134.477 Y116.5 E.10167
G1 X133.9 Y116.5 E.01881
M73 P40 R1
G1 X136.5 Y113.9 E.11983
G1 X136.5 Y113.323 E.01881
G1 X133.323 Y116.5 E.14642
G1 X132.745 Y116.5 E.01881
G1 X136.5 Y112.745 E.17302
G1 X136.5 Y112.168 E.01881
G1 X132.168 Y116.5 E.19961
G1 X131.591 Y116.5 E.01881
G1 X136.5 Y111.591 E.22621
G1 X136.5 Y111.014 E.01881
G1 X131.014 Y116.5 E.2528
G1 X130.437 Y116.5 E.01881
G1 X136.5 Y110.437 E.2794
G1 X136.5 Y109.859 E.01881
M73 P41 R1
G1 X129.859 Y116.5 E.30599
G1 X129.282 Y116.5 E.01881
G1 X136.5 Y109.282 E.33259
G1 X136.5 Y108.705 E.01881
G1 X128.705 Y116.5 E.35918
G1 X128.128 Y116.5 E.01881
G1 X136.5 Y108.128 E.38578
G1 X136.5 Y107.55 E.01881
G1 X127.55 Y116.5 E.41238
G1 X126.973 Y116.5 E.01881
M73 P42 R1
G1 X136.5 Y106.973 E.43897
G1 X136.5 Y106.396 E.01881
G1 X126.396 Y116.5 E.46557
G1 X125.819 Y116.5 E.01881
G1 X136.5 Y105.819 E.49216
G1 X136.5 Y105.242 E.01881
G1 X125.242 Y116.5 E.51876
G1 X124.664 Y116.5 E.01881
G1 X136.5 Y104.664 E.54535
G1 X136.5 Y104.087 E.01881
M73 P43 R1
G1 X124.087 Y116.5 E.57195
G1 X123.51 Y116.5 E.01881
G1 X136.5 Y103.51 E.59854
G1 X136.5 Y102.933 E.01881
G1 X122.933 Y116.5 E.62514
G1 X122.356 Y116.5 E.01881
M73 P44 R1
G1 X136.5 Y102.356 E.65173
G1 X136.5 Y101.778 E.01881
G1 X121.778 Y116.5 E.67833
G1 X121.201 Y116.5 E.01881
G1 X136.5 Y101.201 E.70492
G1 X136.5 Y100.624 E.01881
G1 X120.624 Y116.5 E.73152
G1 X120.047 Y116.5 E.01881
M73 P45 R1
G1 X136.5 Y100.047 E.75811
G1 X136.5 Y99.469 E.01881
G1 X119.469 Y116.5 E.78471
G1 X118.892 Y116.5 E.01881
G1 X136.5 Y98.892 E.8113
G1 X136.5 Y98.315 E.01881
M73 P46 R1
G1 X118.315 Y116.5 E.8379
G1 X117.738 Y116.5 E.01881
G1 X136.5 Y97.738 E.8645
G1 X136.5 Y97.161 E.01881
G1 X117.161 Y116.5 E.89109
G1 X116.583 Y116.5 E.01881
M73 P47 R1
G1 X136.5 Y96.583 E.91769
G1 X136.5 Y96.006 E.01881
G1 X116.006 Y116.5 E.94428
G1 X115.429 Y116.5 E.01881
G1 X136.5 Y95.429 E.97088
M73 P48 R1
G1 X136.5 Y94.852 E.01881
G1 X114.852 Y116.5 E.99747
G1 X114.275 Y116.5 E.01881
G1 X136.5 Y94.275 E1.02407
G1 X136.5 Y93.697 E.01881
M73 P49 R1
G1 X113.697 Y116.5 E1.05066
G1 X113.5 Y116.5 E.00645
G1 X113.5 Y116.121 E.01236
G1 X136.121 Y93.5 E1.0423
G1 X135.544 Y93.5 E.01881
G1 X113.5 Y115.544 E1.0157
M73 P50 R1
G1 X113.5 Y114.967 E.01881
G1 X134.967 Y93.5 E.98911
G1 X134.389 Y93.5 E.01881
G1 X113.5 Y114.389 E.96251
G1 X113.5 Y113.812 E.01881
M73 P51 R1
G1 X133.812 Y93.5 E.93592
G1 X133.235 Y93.5 E.01881
G1 X113.5 Y113.235 E.90932
G1 X113.5 Y112.658 E.01881
G1 X132.658 Y93.5 E.88273
G1 X132.081 Y93.5 E.01881
M73 P52 R1
G1 X113.5 Y112.081 E.85613
G1 X113.5 Y111.503 E.01881
G1 X131.503 Y93.5 E.82953
G1 X130.926 Y93.5 E.01881
G1 X113.5 Y110.926 E.80294
G1 X113.5 Y110.349 E.01881
M73 P53 R1
G1 X130.349 Y93.5 E.77634
G1 X129.772 Y93.5 E.01881
G1 X113.5 Y109.772 E.74975
G1 X113.5 Y109.195 E.01881
G1 X129.195 Y93.5 E.72315
G1 X128.617 Y93.5 E.01881
M73 P54 R1
G1 X113.5 Y108.617 E.69656
G1 X113.5 Y108.04 E.01881
G1 X128.04 Y93.5 E.66996
G1 X127.463 Y93.5 E.01881
G1 X113.5 Y107.463 E.64337
G1 X113.5 Y106.886 E.01881
M73 P55 R1
G1 X126.886 Y93.5 E.61677
G1 X126.308 Y93.5 E.01881
G1 X113.5 Y106.308 E.59018
G1 X113.5 Y105.731 E.01881
G1 X125.731 Y93.5 E.56358
G1 X125.154 Y93.5 E.01881
G1 X113.5 Y105.154 E.53699
G1 X113.5 Y104.577 E.01881
M73 P56 R1
G1 X124.577 Y93.5 E.51039
G1 X124 Y93.5 E.01881
G1 X113.5 Y104 E.4838
G1 X113.5 Y103.422 E.01881
G1 X123.422 Y93.5 E.4572
G1 X122.845 Y93.5 E.01881
G1 X113.5 Y102.845 E.43061
G1 X113.5 Y102.268 E.01881
M73 P57 R1
G1 X122.268 Y93.5 E.40401
G1 X121.691 Y93.5 E.01881
G1 X113.5 Y101.691 E.37741
G1 X113.5 Y101.114 E.01881
G1 X121.114 Y93.5 E.35082
G1 X120.536 Y93.5 E.01881
G1 X113.5 Y100.536 E.32422
G1 X113.5 Y99.959 E.01881
G1 X119.959 Y93.5 E.29763
G1 X119.382 Y93.5 E.01881
M73 P58 R1
G1 X113.5 Y99.382 E.27103
G1 X113.5 Y98.805 E.01881
G1 X118.805 Y93.5 E.24444
G1 X118.228 Y93.5 E.01881
G1 X113.5 Y98.228 E.21784
G1 X113.5 Y97.65 E.01881
G1 X117.65 Y93.5 E.19125
G1 X117.073 Y93.5 E.01881
G1 X113.5 Y97.073 E.16465
G1 X113.5 Y96.496 E.01881
G1 X116.496 Y93.5 E.13806
G1 X115.919 Y93.5 E.01881
G1 X113.5 Y95.919 E.11146
G1 X113.5 Y95.341 E.01881
M73 P59 R1
G1 X115.341 Y93.5 E.08487
G1 X114.764 Y93.5 E.01881
G1 X113.5 Y94.764 E.05827
G1 X113.5 Y94.187 E.01881
M73 P59 R0
G1 X114.37 Y93.316 E.04012
M204 S180
G1 X113.601 Y93.527 F7200
M204 S500
;WIDTH:0.477236
G1 F4200
G1 X113.547 Y93.527 E.00188
G1 X113.52 Y93.574 E.00188
G1 X113.547 Y93.621 E.00188
G1 X113.601 Y93.621 E.00188
G1 X113.609 Y93.609 E.0005
; stop printing object Cube id:13844432977387129179 copy 0
;LAYER_CHANGE
M117 DASHBOARD_LAYER_INDICATOR 3
M118 E1 OCTOAPP_LAYER LAYER=2
M117 DASHBOARD_LAYER_INDICATOR 3
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.6
G1 E-.70081 F1800
;WIPE_START
G1 F4200
G1 X113.601 Y93.621 E-.00612
G1 X113.547 Y93.621 E-.02327
G1 X113.52 Y93.574 E-.02327
G1 X113.547 Y93.527 E-.02327
G1 X113.601 Y93.527 E-.02327
;WIPE_END
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object Cube id:13844432977387129179 copy 0
M204 S180
G1 X118.99 Y98.933 Z1 F7200
G1 X136.846 Y116.846 Z1
G1 Z.6
M73 P60 R0
G1 E.8 F1800
M204 S300
;TYPE:Inner wall
;WIDTH:0.449999
G1 F3600
G1 X113.154 Y116.846 E.7699
G1 X113.154 Y93.154 E.7699
G1 X136.846 Y93.154 E.7699
G1 X136.846 Y116.806 E.7686
M73 P61 R0
M204 S180
G1 X137.275 Y117.275 F7200
M204 S500
;TYPE:Outer wall
G1 F3600
G1 X112.725 Y117.275 E.79775
G1 X112.725 Y92.725 E.79775
M73 P62 R0
G1 X137.275 Y92.725 E.79775
G1 X137.275 Y117.235 E.79645
M204 S180
G1 E-.3 F1800
M73 P63 R0
;WIPE_START
G1 F3600
G1 X136.275 Y117.237 E-.5
;WIPE_END
G1 X136.423 Y109.606 Z1 F7200
G1 X136.727 Y93.995 Z1
G1 Z.6
G1 E.8 F1800
M204 S500
;TYPE:Top surface
;WIDTH:0.400113
G1 F2400
G1 X136.005 Y93.273 E.02912
M204 S180
G1 X135.5 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y94.5 E.04949
M204 S180
G1 X136.727 Y95.006 F7200
M204 S500
G1 F2400
M73 P64 R0
G1 X134.994 Y93.273 E.06985
M204 S180
G1 X134.489 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y95.511 E.09022
M204 S180
G1 X136.727 Y96.016 F7200
M204 S500
G1 F2400
G1 X133.984 Y93.273 E.11059
M204 S180
G1 X133.479 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y96.521 E.13096
M204 S180
G1 X136.727 Y97.026 F7200
M204 S500
G1 F2400
G1 X132.974 Y93.273 E.15133
M204 S180
G1 X132.469 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y97.531 E.1717
M204 S180
G1 X136.727 Y98.036 F7200
M204 S500
G1 F2400
G1 X131.964 Y93.273 E.19207
M204 S180
G1 X131.458 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y98.542 E.21244
M204 S180
G1 X136.727 Y99.047 F7200
M73 P65 R0
M204 S500
G1 F2400
G1 X130.953 Y93.273 E.23281
M204 S180
G1 X130.448 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y99.552 E.25318
M204 S180
G1 X136.727 Y100.057 F7200
M204 S500
G1 F2400
G1 X129.943 Y93.273 E.27355
M204 S180
G1 X129.438 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y100.562 E.29391
M204 S180
G1 X136.727 Y101.067 F7200
M73 P66 R0
M204 S500
G1 F2400
G1 X128.933 Y93.273 E.31428
M204 S180
G1 X128.428 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y101.572 E.33465
M204 S180
G1 X136.727 Y102.078 F7200
M204 S500
G1 F2400
G1 X127.922 Y93.273 E.35502
M204 S180
G1 X127.417 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y102.583 E.37539
M204 S180
G1 X136.727 Y103.088 F7200
M73 P67 R0
M204 S500
G1 F2400
G1 X126.912 Y93.273 E.39576
M204 S180
G1 X126.407 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y103.593 E.41613
M204 S180
G1 X136.727 Y104.098 F7200
M204 S500
G1 F2400
G1 X125.902 Y93.273 E.4365
M204 S180
G1 X125.397 Y93.273 F7200
M73 P68 R0
M204 S500
G1 F2400
G1 X136.727 Y104.603 E.45687
M204 S180
G1 X136.727 Y105.108 F7200
M204 S500
G1 F2400
G1 X124.892 Y93.273 E.47724
M204 S180
G1 X124.386 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y105.614 E.49761
M204 S180
G1 X136.727 Y106.119 F7200
M73 P69 R0
M204 S500
G1 F2400
G1 X123.881 Y93.273 E.51797
M204 S180
G1 X123.376 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y106.624 E.53834
M204 S180
G1 X136.727 Y107.129 F7200
M204 S500
G1 F2400
G1 X122.871 Y93.273 E.55871
M204 S180
G1 X122.366 Y93.273 F7200
M73 P70 R0
M204 S500
G1 F2400
G1 X136.727 Y107.634 E.57908
M204 S180
G1 X136.727 Y108.139 F7200
M204 S500
G1 F2400
G1 X121.861 Y93.273 E.59945
M204 S180
G1 X121.355 Y93.273 F7200
M73 P71 R0
M204 S500
G1 F2400
G1 X136.727 Y108.645 E.61982
M204 S180
G1 X136.727 Y109.15 F7200
M204 S500
G1 F2400
G1 X120.85 Y93.273 E.64019
M204 S180
G1 X120.345 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y109.655 E.66056
M204 S180
G1 X136.727 Y110.16 F7200
M73 P72 R0
M204 S500
G1 F2400
G1 X119.84 Y93.273 E.68093
M204 S180
G1 X119.335 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y110.665 E.7013
M204 S180
G1 X136.727 Y111.17 F7200
M73 P73 R0
M204 S500
G1 F2400
G1 X118.83 Y93.273 E.72166
M204 S180
G1 X118.325 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y111.675 E.74203
M204 S180
G1 X136.727 Y112.181 F7200
M73 P74 R0
M204 S500
G1 F2400
G1 X117.819 Y93.273 E.7624
M204 S180
G1 X117.314 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y112.686 E.78277
M204 S180
G1 X136.727 Y113.191 F7200
M73 P75 R0
M204 S500
G1 F2400
G1 X116.809 Y93.273 E.80314
M204 S180
G1 X116.304 Y93.273 F7200
M204 S500
G1 F2400
G1 X136.727 Y113.696 E.82351
M204 S180
G1 X136.727 Y114.201 F7200
M73 P76 R0
M204 S500
G1 F2400
G1 X115.799 Y93.273 E.84388
M204 S180
G1 X115.294 Y93.273 F7200
M73 P77 R0
M204 S500
G1 F2400
G1 X136.727 Y114.706 E.86425
M204 S180
G1 X136.727 Y115.211 F7200
M204 S500
G1 F2400
G1 X114.789 Y93.273 E.88462
M204 S180
G1 X114.283 Y93.273 F7200
M73 P78 R0
M204 S500
G1 F2400
G1 X136.727 Y115.717 E.90499
M204 S180
G1 X136.727 Y116.222 F7200
M204 S500
G1 F2400
G1 X113.778 Y93.273 E.92536
M204 S180
G1 X113.273 Y93.273 F7200
M73 P79 R0
M204 S500
G1 F2400
G1 X136.727 Y116.727 E.94572
M204 S180
G1 X136.222 Y116.727 F7200
M73 P80 R0
M204 S500
G1 F2400
G1 X113.273 Y93.778 E.92535
M204 S180
G1 X113.273 Y94.283 F7200
M204 S500
G1 F2400
G1 X135.717 Y116.727 E.90498
M204 S180
G1 X135.211 Y116.727 F7200
M73 P81 R0
M204 S500
G1 F2400
G1 X113.273 Y94.789 E.88462
M204 S180
G1 X113.273 Y95.294 F7200
M204 S500
G1 F2400
G1 X134.706 Y116.727 E.86425
M204 S180
G1 X134.201 Y116.727 F7200
M73 P82 R0
M204 S500
G1 F2400
G1 X113.273 Y95.799 E.84388
M204 S180
G1 X113.273 Y96.304 F7200
M73 P83 R0
M204 S500
G1 F2400
G1 X133.696 Y116.727 E.82351
M204 S180
G1 X133.191 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y96.809 E.80314
M204 S180
G1 X113.273 Y97.314 F7200
M73 P84 R0
M204 S500
G1 F2400
G1 X132.686 Y116.727 E.78277
M204 S180
G1 X132.18 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y97.82 E.7624
M204 S180
G1 X113.273 Y98.325 F7200
M73 P85 R0
M204 S500
G1 F2400
G1 X131.675 Y116.727 E.74203
M204 S180
G1 X131.17 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y98.83 E.72166
M204 S180
G1 X113.273 Y99.335 F7200
M73 P86 R0
M204 S500
G1 F2400
G1 X130.665 Y116.727 E.70129
M204 S180
G1 X130.16 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y99.84 E.68092
M204 S180
G1 X113.273 Y100.345 F7200
M73 P87 R0
M204 S500
G1 F2400
G1 X129.655 Y116.727 E.66056
M204 S180
G1 X129.15 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y100.85 E.64019
M204 S180
G1 X113.273 Y101.356 F7200
M204 S500
G1 F2400
G1 X128.644 Y116.727 E.61982
M204 S180
G1 X128.139 Y116.727 F7200
M73 P88 R0
M204 S500
G1 F2400
G1 X113.273 Y101.861 E.59945
M204 S180
G1 X113.273 Y102.366 F7200
M204 S500
G1 F2400
G1 X127.634 Y116.727 E.57908
M204 S180
G1 X127.129 Y116.727 F7200
M73 P89 R0
M204 S500
G1 F2400
G1 X113.273 Y102.871 E.55871
M204 S180
G1 X113.273 Y103.376 F7200
M204 S500
G1 F2400
G1 X126.624 Y116.727 E.53834
M204 S180
G1 X126.119 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y103.881 E.51797
M204 S180
G1 X113.273 Y104.386 F7200
M73 P90 R0
M204 S500
G1 F2400
G1 X125.614 Y116.727 E.4976
M204 S180
G1 X125.108 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y104.892 E.47723
M204 S180
G1 X113.273 Y105.397 F7200
M73 P91 R0
M204 S500
G1 F2400
G1 X124.603 Y116.727 E.45686
M204 S180
G1 X124.098 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y105.902 E.4365
M204 S180
G1 X113.273 Y106.407 F7200
M204 S500
G1 F2400
G1 X123.593 Y116.727 E.41613
M204 S180
G1 X123.088 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y106.912 E.39576
M204 S180
G1 X113.273 Y107.417 F7200
M73 P92 R0
M204 S500
G1 F2400
G1 X122.583 Y116.727 E.37539
M204 S180
G1 X122.078 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y107.922 E.35502
M204 S180
G1 X113.273 Y108.428 F7200
M204 S500
G1 F2400
G1 X121.572 Y116.727 E.33465
M204 S180
G1 X121.067 Y116.727 F7200
M73 P93 R0
M204 S500
G1 F2400
G1 X113.273 Y108.933 E.31428
M204 S180
G1 X113.273 Y109.438 F7200
M204 S500
G1 F2400
G1 X120.562 Y116.727 E.29391
M204 S180
G1 X120.057 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y109.943 E.27354
M204 S180
G1 X113.273 Y110.448 F7200
M204 S500
G1 F2400
G1 X119.552 Y116.727 E.25317
M204 S180
G1 X119.047 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y110.953 E.2328
M204 S180
G1 X113.273 Y111.458 F7200
M73 P94 R0
M204 S500
G1 F2400
G1 X118.542 Y116.727 E.21244
M204 S180
G1 X118.036 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y111.964 E.19207
M204 S180
G1 X113.273 Y112.469 F7200
M204 S500
G1 F2400
G1 X117.531 Y116.727 E.1717
M204 S180
G1 X117.026 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y112.974 E.15133
M204 S180
G1 X113.273 Y113.479 F7200
M204 S500
G1 F2400
G1 X116.521 Y116.727 E.13096
M204 S180
G1 X116.016 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y113.984 E.11059
M204 S180
G1 X113.273 Y114.489 F7200
M73 P95 R0
M204 S500
G1 F2400
G1 X115.511 Y116.727 E.09022
M204 S180
G1 X115.005 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y114.995 E.06985
M204 S180
G1 X113.273 Y115.5 F7200
M204 S500
G1 F2400
G1 X114.5 Y116.727 E.04948
M204 S180
G1 X113.995 Y116.727 F7200
M204 S500
G1 F2400
G1 X113.273 Y116.005 E.02911
; stop printing object Cube id:13844432977387129179 copy 0
G1 E-.08 F1800
;WIPE_START
G1 F2400
G1 X113.98 Y116.712 E-.72
;WIPE_END
M106 S0
;TYPE:Custom
; filament end gcode
G1 Z1.6 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z49.6 F720 ; Move print head further up
M73 P97 R0
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; EXECUTABLE_BLOCK_END
; filament used [mm] = 178.83
; filament used [cm3] = 0.43
; filament used [g] = 0.56
; filament cost = 0.01
; total filament used [g] = 0.56
; total filament cost = 0.01
; total layers count = 3
; estimated printing time (normal mode) = 2m 25s
; estimated first layer printing time (normal mode) = 8s
; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 70
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = C:\\Users\\jensm\\Desktop\\mk2_bed.stl
; bed_custom_texture = C:\\Users\\jensm\\Desktop\\mk2.svg
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 25
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0
; brim_type = no_brim
; brim_width = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = M600
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = partiallybridge
; curr_bed_type = High Temp Plate
; default_acceleration = 500
; default_filament_colour = ""
; default_filament_profile = "Prusament PLA"
; default_jerk = 0
; default_print_profile = 0.15mm OPTIMAL
; deretraction_speed = 0
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = brim_type;counterbore_hole_bridging;elefant_foot_compensation;enable_support;gap_infill_speed;initial_layer_speed;inner_wall_acceleration;internal_solid_infill_speed;precise_outer_wall;skirt_loops;sparse_infill_pattern;sparse_infill_speed;support_speed;top_surface_speed;travel_acceleration;compatible_printers;filament_flow_ratio;bed_custom_model;bed_custom_texture;before_layer_change_gcode;change_filament_gcode;default_filament_profile;default_print_profile;deretraction_speed;extruder_clearance_height_to_lid;extruder_clearance_height_to_rod;extruder_clearance_radius;extruder_colour;gcode_flavor;layer_change_gcode;machine_end_gcode;machine_max_acceleration_e;machine_max_acceleration_extruding;machine_max_acceleration_retracting;machine_max_acceleration_travel;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_acceleration_z;machine_max_jerk_e;machine_max_jerk_x;machine_max_jerk_y;machine_max_jerk_z;machine_max_speed_e;machine_max_speed_x;machine_max_speed_y;machine_max_speed_z;machine_min_extruding_rate;machine_min_travel_rate;machine_pause_gcode;machine_start_gcode;max_layer_height;min_layer_height;nozzle_type;print_host;printable_area;printable_height;printer_model;printer_notes;printer_variant;printhost_apikey;retract_before_wipe;retract_length_toolchange;retract_lift_below;retraction_minimum_travel;support_multi_bed_types;thumbnails;z_hop_types
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0.2
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 0
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 120
; extruder_clearance_height_to_rod = 40
; extruder_clearance_radius = 40
; extruder_colour = #FF8000
; extruder_offset = 0x0
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.31
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_flow_ratio = 0.96
; filament_ids = GFL01
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 22
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "PolyTerra PLA @System - Copy"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; Filament gcode\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Polymaker
; filename_format = {input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 1
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 40
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 55
; hot_plate_temp_initial_layer = 55
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 15%
; inherits_group = Untitled;"PolyTerra PLA @System";"MyKlipper 0.4 nozzle"
; initial_layer_acceleration = 300
; initial_layer_infill_speed = 60
; initial_layer_jerk = 9
; initial_layer_line_width = 0
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 20
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 300
; inner_wall_jerk = 9
; inner_wall_line_width = 0
; inner_wall_speed = 60
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 70
; ironing_angle = -1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = zig-zag
; ironing_spacing = 0.1
; ironing_speed = 20
; ironing_type = no ironing
; is_infill_first = 0
; lattice_angle_1 = -45
; lattice_angle_2 = 45
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0
; long_retractions_when_cut = 0
; machine_end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM900 K0 ; reset LA\nM84 ; disable motors
; machine_load_filament_time = 0
; machine_max_acceleration_e = 800
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000
; machine_max_acceleration_y = 1000
; machine_max_acceleration_z = 200
; machine_max_jerk_e = 5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.4
; machine_max_speed_e = 120
; machine_max_speed_x = 200
; machine_max_speed_y = 200
; machine_max_speed_z = 12
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = M601
; machine_start_gcode = M862.3 P \"[printer_model]\" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.2.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM204 S[machine_max_acceleration_extruding] T[machine_max_acceleration_retracting] ; MK2 firmware only supports the old M204 format\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Z2.0 F3000 ;Move Z Axis up\nG1 X{first_layer_print_min[0]-10} Y{first_layer_print_min[1]} Z0.8 F5000 ; Move to start\nM109 S[nozzle_temperature_initial_layer] ; wait for nozzle temp to stabilize\nG92 E0 ;Reset Extruder\nG1 X{first_layer_print_min[0]-10} Y{first_layer_print_min[1]+30} E30 F360.0 ; Extrude 30mm in Y\nG92 E0 ;Reset Extruder\nG1 E-0.5 F2100 ; Retract\nG1 Y{first_layer_print_min[1]+40} F5000 ; Move 10mm in Y\nG92 E0  ;Reset Extrude
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.25
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.07
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 220
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 500
; outer_wall_jerk = 9
; outer_wall_line_width = 0
; outer_wall_speed = 60
; overhang_1_4_speed = 0
; overhang_2_4_speed = 0
; overhang_3_4_speed = 0
; overhang_4_4_speed = 0
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = Standard
; printable_area = 0x0,250x0,250x210,0x210
; printable_height = 210
; printer_model = 
; printer_notes = Don't remove the following keywords! These keywords are used in the \"compatible printer\" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK2\n
; printer_settings_id = Pretty PLA (Testi uus prime)
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 0
; required_nozzle_HRC = 3
; resolution = 0.01
; retract_before_wipe = 10%
; retract_length_toolchange = 4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_lift_enforce = All Surfaces
; retract_on_top_layer = 1
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.8
; retraction_minimum_travel = 2
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 1
; single_loop_draft_shield = 0
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 4
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 20%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0
; sparse_infill_pattern = cubic
; sparse_infill_speed = 70
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 45
; supertack_plate_temp_initial_layer = 45
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = 0
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 3
; support_line_width = 0
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 1
; support_object_first_layer_gap = 0.2
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 50
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = tree(manual)
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 55
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG, 300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 4
; top_shell_thickness = 0.6
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 500
; top_surface_jerk = 9
; top_surface_line_width = 0
; top_surface_pattern = monotonicline
; top_surface_speed = 40
; travel_acceleration = 180
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 120
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 40
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Slope Lift
; z_offset = 0
; first_layer_bed_temperature = 55
; bed_shape = 0x0,250x0,250x210,0x210
; first_layer_temperature = 220
; first_layer_height = 0.200
; CONFIG_BLOCK_END
